In [1]:
from _setup import setup_project_root
PROJECT_ROOT = setup_project_root()
PROJECT_ROOT

WindowsPath('C:/Users/huyy/AirPollutionPrediction-CNN-BiLSTM')

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path
import joblib
import tensorflow as tf
from tensorflow.keras.models import load_model

In [3]:
PROJECT_ROOT = Path.cwd().parent
DATA_DIR = PROJECT_ROOT / "data"
STATION_SPLIT_DIR = DATA_DIR / "station_split"

In [4]:
from models.cnn_bilstm import train_cnn_bilstm, predict_cnn_bilstm
from evaluation.metrics import compute_metrics_real_scale

In [5]:
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"
ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
pm25_scaler = joblib.load(ARTIFACTS_DIR / "pm25_scaler.pkl")

In [6]:
target_col = "PM2.5"
id_cols = ["Station_No", "date"]

In [ ]:
SEQ_LEN = 48
EPOCHS = 200
BATCH = 64

all_results = []

In [8]:
station_dirs = sorted([p for p in STATION_SPLIT_DIR.glob("station_*") if p.is_dir()],
                      key=lambda x: int(x.name.split("_")[1]))

In [ ]:
for st_dir in station_dirs:
    st = int(st_dir.name.split("_")[1])
    train_path = st_dir / "train.csv"
    val_path   = st_dir / "val.csv"
    test_path  = st_dir / "test.csv"

    train_df = pd.read_csv(train_path); train_df["date"] = pd.to_datetime(train_df["date"])
    val_df   = pd.read_csv(val_path);   val_df["date"]   = pd.to_datetime(val_df["date"])
    test_df  = pd.read_csv(test_path);  test_df["date"]  = pd.to_datetime(test_df["date"])

    feature_cols = [c for c in train_df.columns if c not in id_cols + [target_col]]

    X_train = train_df[feature_cols].values.astype(np.float32)
    y_train = train_df[target_col].values.astype(np.float32)

    X_val = val_df[feature_cols].values.astype(np.float32)
    y_val = val_df[target_col].values.astype(np.float32)

    X_test = test_df[feature_cols].values.astype(np.float32)
    y_test = test_df[target_col].values.astype(np.float32)

    ckpt_path = ARTIFACTS_DIR / f"cnn_bilstm_station{st}_best_seq{SEQ_LEN}_u256.keras"

    # Train
    model, history = train_cnn_bilstm(
        X_train, y_train,
        X_val, y_val,
        seq_len=SEQ_LEN,
        epochs=EPOCHS,
        batch_size=BATCH,
        use_early_stopping=True,
        patience=20,
        learning_rate=3e-4,
        lstm_units=192,
        use_attention=True,
        checkpoint_path=str(ckpt_path)
    )

    # Predict using best checkpoint
    best_model = load_model(ckpt_path)
    y_pred_scaled = predict_cnn_bilstm(best_model, X_test, seq_len=SEQ_LEN)
    y_true_scaled = y_test[SEQ_LEN:]

    metrics = compute_metrics_real_scale(
        y_true_scaled=y_true_scaled,
        y_pred_scaled=y_pred_scaled,
        scaler=pm25_scaler,
        eps=1.0,
        mask_nan=True
    )

    row = {"Station_No": st, "n_test": int(len(y_true_scaled))}
    row.update(metrics)
    all_results.append(row)

    print(f"Done station {st} | Corr={metrics['Correlation']:.3f} RMSE={metrics['RMSE']:.2f} MAE={metrics['MAE']:.2f} MAPE={metrics['MAPE']:.3f}")

Epoch 1/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.1860
Epoch 1: val_loss improved from None to 0.01270, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 214s 1s/step - loss: 0.0657 - val_loss: 0.0127 - learning_rate: 3.0000e-04
Epoch 2/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0148
Epoch 2: val_loss improved from 0.01270 to 0.01233, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 161s 1s/step - loss: 0.0141 - val_loss: 0.0123 - learning_rate: 3.0000e-04
Epoch 3/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 2s/step - loss: 0.0117
Epoch 3: val_loss did not improve from 0.01233
126/126 ━━━━━━━━━━━━━━━━━━━━ 334s 2s/step - loss: 0.0120 - val_loss: 0.0129 - learning_rate: 3.0000e-04
Epoch 4/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 3s/step - loss: 0.0113
Epoch 4: val_loss improved from 0.01233 to 0.00934, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 443s 3s/step - loss: 0.0109 - val_loss: 0.0093 - learning_rate: 3.0000e-04
Epoch 5/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 3s/step - loss: 0.0097
Epoch 5: val_loss improved from 0.00934 to 0.00773, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 368s 3s/step - loss: 0.0095 - val_loss: 0.0077 - learning_rate: 3.0000e-04
Epoch 6/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 2s/step - loss: 0.0089
Epoch 6: val_loss improved from 0.00773 to 0.00646, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 253s 2s/step - loss: 0.0084 - val_loss: 0.0065 - learning_rate: 3.0000e-04
Epoch 7/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 2s/step - loss: 0.0075
Epoch 7: val_loss improved from 0.00646 to 0.00622, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 355s 3s/step - loss: 0.0075 - val_loss: 0.0062 - learning_rate: 3.0000e-04
Epoch 8/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 3s/step - loss: 0.0073
Epoch 8: val_loss improved from 0.00622 to 0.00566, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 389s 3s/step - loss: 0.0071 - val_loss: 0.0057 - learning_rate: 3.0000e-04
Epoch 9/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 2s/step - loss: 0.0066
Epoch 9: val_loss improved from 0.00566 to 0.00529, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 323s 3s/step - loss: 0.0067 - val_loss: 0.0053 - learning_rate: 3.0000e-04
Epoch 10/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 2s/step - loss: 0.0063
Epoch 10: val_loss improved from 0.00529 to 0.00499, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 251s 2s/step - loss: 0.0060 - val_loss: 0.0050 - learning_rate: 3.0000e-04
Epoch 11/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 2s/step - loss: 0.0064
Epoch 11: val_loss did not improve from 0.00499
126/126 ━━━━━━━━━━━━━━━━━━━━ 247s 2s/step - loss: 0.0060 - val_loss: 0.0055 - learning_rate: 3.0000e-04
Epoch 12/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 2s/step - loss: 0.0058
Epoch 12: val_loss did not improve from 0.00499
126/126 ━━━━━━━━━━━━━━━━━━━━ 269s 2s/step - loss: 0.0057 - val_loss: 0.0058 - learning_rate: 3.0000e-04
Epoch 13/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 3s/step - loss: 0.0054
Epoch 13: val_loss improved from 0.00499 to 0.00454, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 343s 3s/step - loss: 0.0054 - val_loss: 0.0045 - learning_rate: 3.0000e-04
Epoch 14/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 2s/step - loss: 0.0054
Epoch 14: val_loss improved from 0.00454 to 0.00453, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 229s 2s/step - loss: 0.0053 - val_loss: 0.0045 - learning_rate: 3.0000e-04
Epoch 15/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0053
Epoch 15: val_loss did not improve from 0.00453
126/126 ━━━━━━━━━━━━━━━━━━━━ 170s 1s/step - loss: 0.0052 - val_loss: 0.0047 - learning_rate: 3.0000e-04
Epoch 16/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0050
Epoch 16: val_loss improved from 0.00453 to 0.00428, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 187s 1s/step - loss: 0.0050 - val_loss: 0.0043 - learning_rate: 3.0000e-04
Epoch 17/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0051
Epoch 17: val_loss did not improve from 0.00428
126/126 ━━━━━━━━━━━━━━━━━━━━ 190s 2s/step - loss: 0.0052 - val_loss: 0.0043 - learning_rate: 3.0000e-04
Epoch 18/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0047
Epoch 18: val_loss improved from 0.00428 to 0.00419, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 192s 2s/step - loss: 0.0048 - val_loss: 0.0042 - learning_rate: 3.0000e-04
Epoch 19/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0049
Epoch 19: val_loss improved from 0.00419 to 0.00418, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 192s 2s/step - loss: 0.0047 - val_loss: 0.0042 - learning_rate: 3.0000e-04
Epoch 20/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0047
Epoch 20: val_loss improved from 0.00418 to 0.00392, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 191s 2s/step - loss: 0.0048 - val_loss: 0.0039 - learning_rate: 3.0000e-04
Epoch 21/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0047
Epoch 21: val_loss did not improve from 0.00392
126/126 ━━━━━━━━━━━━━━━━━━━━ 190s 2s/step - loss: 0.0046 - val_loss: 0.0040 - learning_rate: 3.0000e-04
Epoch 22/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0045
Epoch 22: val_loss did not improve from 0.00392
126/126 ━━━━━━━━━━━━━━━━━━━━ 197s 2s/step - loss: 0.0044 - val_loss: 0.0041 - learning_rate: 3.0000e-04
Epoch 23/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0042
Epoch 23: val_loss improved from 0.00392 to 0.00383, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 190s 2s/step - loss: 0.0043 - val_loss: 0.0038 - learning_rate: 3.0000e-04
Epoch 24/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0043
Epoch 24: val_loss improved from 0.00383 to 0.00379, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 191s 2s/step - loss: 0.0044 - val_loss: 0.0038 - learning_rate: 3.0000e-04
Epoch 25/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0041
Epoch 25: val_loss did not improve from 0.00379
126/126 ━━━━━━━━━━━━━━━━━━━━ 190s 2s/step - loss: 0.0041 - val_loss: 0.0042 - learning_rate: 3.0000e-04
Epoch 26/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0041
Epoch 26: val_loss did not improve from 0.00379
126/126 ━━━━━━━━━━━━━━━━━━━━ 192s 2s/step - loss: 0.0040 - val_loss: 0.0042 - learning_rate: 3.0000e-04
Epoch 27/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0041
Epoch 27: val_loss did not improve from 0.00379
126/126 ━━━━━━━━━━━━━━━━━━━━ 180s 1s/step - loss: 0.0040 - val_loss: 0.0041 - learning_rate: 3.0000e-04
Epoch 28/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0040
Epoch 28: val_loss did not improve from 0.00379
126/126 ━━━━━━━━━━━━━━━━━━━━ 173s 1s/step - loss: 0.0040 - val_loss: 0.0045 - learning_rate: 3.0000e-04
Epoch 29/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0040
Epoch 29: val_loss did not improve from 0.00379
126/126 ━━━━━━━━━━━━━━━━━━━━ 171s 1s/step - loss: 0.0039 - val_loss: 0.0045 - learning_rate: 3.0000e-04
Epoch 30/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0038
Epoch 30: val_loss did not improve from 0.00379
126/126 ━━━━━━━━━━━━━━━━━━━━ 179s 1s/step - loss: 0.0039 - val_loss: 0.0041 - learning_rate: 3.0000e-04
Epoch 31/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0037
Epoch 31: val_loss did not improve from 0.00379
126/126 ━━━━━━━━━━━━━━━━━━━━ 202s 1s/step - loss: 0.0038 - val_loss: 0.0043 - learning_rate: 3.0000e-04
Epoch 32/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0039
Epoch 32: val_loss improved from 0.00379 to 0.00355, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 180s 1s/step - loss: 0.0038 - val_loss: 0.0036 - learning_rate: 3.0000e-04
Epoch 33/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0035
Epoch 33: val_loss did not improve from 0.00355
126/126 ━━━━━━━━━━━━━━━━━━━━ 174s 1s/step - loss: 0.0036 - val_loss: 0.0040 - learning_rate: 3.0000e-04
Epoch 34/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0037
Epoch 34: val_loss did not improve from 0.00355
126/126 ━━━━━━━━━━━━━━━━━━━━ 173s 1s/step - loss: 0.0037 - val_loss: 0.0043 - learning_rate: 3.0000e-04
Epoch 35/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0036
Epoch 35: val_loss did not improve from 0.00355
126/126 ━━━━━━━━━━━━━━━━━━━━ 176s 1s/step - loss: 0.0035 - val_loss: 0.0037 - learning_rate: 3.0000e-04
Epoch 36/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0036
Epoch 36: val_loss did not improve from 0.00355
126/126 ━━━━━━━━━━━━━━━━━━━━ 176s 1s/step - loss: 0.0036 - val_loss: 0.0036 - learning_rate: 3.0000e-04
Epoch 37/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0037
Epoch 37: val_loss did not improve from 0.00355
126/126 ━━━━━━━━━━━━━━━━━━━━ 165s 1s/step - loss: 0.0036 - val_loss: 0.0036 - learning_rate: 3.0000e-04
Epoch 38/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0033
Epoch 38: val_loss did not improve from 0.00355
126/126 ━━━━━━━━━━━━━━━━━━━━ 176s 1s/step - loss: 0.0035 - val_loss: 0.0040 - learning_rate: 3.0000e-04
Epoch 39/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0035
Epoch 39: val_loss did not improve from 0.00355
126/126 ━━━━━━━━━━━━━━━━━━━━ 175s 1s/step - loss: 0.0034 - val_loss: 0.0040 - learning_rate: 3.0000e-04
Epoch 40/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0034
Epoch 40: val_loss did not improve from 0.00355
126/126 ━━━━━━━━━━━━━━━━━━━━ 171s 1s/step - loss: 0.0034 - val_loss: 0.0040 - learning_rate: 3.0000e-04
Epoch 41/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0035
Epoch 41: val_loss did not improve from 0.00355
126/126 ━━━━━━━━━━━━━━━━━━━━ 175s 1s/step - loss: 0.0034 - val_loss: 0.0039 - learning_rate: 3.0000e-04
Epoch 42/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0035
Epoch 42: val_loss did not improve from 0.00355

Epoch 42: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.
126/126 ━━━━━━━━━━━━━━━━━━━━ 165s 1s/step - loss: 0.0033 - val_loss: 0.0051 - learning_rate: 3.0000e-04
Epoch 43/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0032
Epoch 43: val_loss did not improve from 0.00355
126/126 ━━━━━━━━━━━━━━━━━━━━ 163s 1s/step - loss: 0.0032 - val_loss: 0.0038 - learning_rate: 1.5000e-04
Epoch 44/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0032
Epoch 44: val_loss did not improve from 0.00355
126/126 ━━━━━━━━━━━━━━━━━━━━ 166s 1s/step - loss: 0.0032 - val_loss: 0.0036 - learning_rate: 1.5000e-04
Epoch 45/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0031
Epoch 45: val_loss did not improve from 0.00355
126/126 ━━━━━━━━━━━━━━━━━━━━ 170s 1s/step - loss: 0.0031 - val_loss: 0.0037 - learning_rate: 1.5000e-04
Epoch 46/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0033
Epoch 46: val_loss did not improve from 0.00355
126/126 ━━━━━━━━━━━━━━━━━━━━ 174s 1s/step - loss: 0.0031 - val_loss: 0.0038 - learning_rate: 1.5000e-04
Epoch 47/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0030
Epoch 47: val_loss did not improve from 0.00355
126/126 ━━━━━━━━━━━━━━━━━━━━ 166s 1s/step - loss: 0.0032 - val_loss: 0.0037 - learning_rate: 1.5000e-04
Epoch 48/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0029
Epoch 48: val_loss did not improve from 0.00355
126/126 ━━━━━━━━━━━━━━━━━━━━ 164s 1s/step - loss: 0.0030 - val_loss: 0.0040 - learning_rate: 1.5000e-04
Epoch 49/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0031
Epoch 49: val_loss improved from 0.00355 to 0.00351, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 155s 1s/step - loss: 0.0030 - val_loss: 0.0035 - learning_rate: 1.5000e-04
Epoch 50/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0030
Epoch 50: val_loss did not improve from 0.00351
126/126 ━━━━━━━━━━━━━━━━━━━━ 157s 1s/step - loss: 0.0030 - val_loss: 0.0037 - learning_rate: 1.5000e-04
Epoch 51/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0030
Epoch 51: val_loss did not improve from 0.00351
126/126 ━━━━━━━━━━━━━━━━━━━━ 218s 1s/step - loss: 0.0032 - val_loss: 0.0040 - learning_rate: 1.5000e-04
Epoch 52/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0031
Epoch 52: val_loss did not improve from 0.00351

Epoch 52: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
126/126 ━━━━━━━━━━━━━━━━━━━━ 167s 1s/step - loss: 0.0030 - val_loss: 0.0038 - learning_rate: 1.5000e-04
Epoch 53/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0029
Epoch 53: val_loss did not improve from 0.00351
126/126 ━━━━━━━━━━━━━━━━━━━━ 142s 1s/step - loss: 0.0029 - val_loss: 0.0036 - learning_rate: 7.5000e-05
Epoch 54/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 955ms/step - loss: 0.0028
Epoch 54: val_loss did not improve from 0.00351
126/126 ━━━━━━━━━━━━━━━━━━━━ 127s 1s/step - loss: 0.0029 - val_loss: 0.0040 - learning_rate: 7.5000e-05
Epoch 55/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 817ms/step - loss: 0.0029
Epoch 55: val_loss did not improve from 0.00351
126/126 ━━━━━━━━━━━━━━━━━━━━ 110s 874ms/step - loss: 0.0029 - val_loss: 0.0037 - learning_rate: 7.5000e-05
Epoch 56/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 684ms/step - loss: 0.0029
Epoch 56: val_loss did not improve from 0.00351
126/126 ━━━━━━━━━━━━━━━━━━━━ 126s 750ms/step - loss: 0.0029 - val_loss: 0.0038 - learning_rate: 7.5000e-05
Epoch 57/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 798ms/step - loss: 0.0029
Epoch 57: val_loss did not improve from 0.00351
126/126 ━━━━━━━━━━━━━━━━━━━━ 107s 849ms/step - loss: 0.0029 - val_loss: 0.0036 - learning_rate: 7.5000e-05
Epoch 58/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 781ms/step - loss: 0.0027
Epoch 58: val_loss did not improve from 0.00351
126/126 ━━━━━━━━━━━━━━━━━━━━ 105s 838ms/step - loss: 0.0028 - val_loss: 0.0037 - learning_rate: 7.5000e-05
Epoch 59/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 787ms/step - loss: 0.0029
Epoch 59: val_loss did not improve from 0.00351
126/126 ━━━━━━━━━━━━━━━━━━━━ 106s 840ms/step - loss: 0.0029 - val_loss: 0.0036 - learning_rate: 7.5000e-05
Epoch 60/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 803ms/step - loss: 0.0029
Epoch 60: val_loss did not improve from 0.00351
126/126 ━━━━━━━━━━━━━━━━━━━━ 110s 877ms/step - loss: 0.0028 - val_loss: 0.0037 - learning_rate: 7.5000e-05
Epoch 61/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 838ms/step - loss: 0.0030
Epoch 61: val_loss did not improve from 0.00351
126/126 ━━━━━━━━━━━━━━━━━━━━ 116s 923ms/step - loss: 0.0028 - val_loss: 0.0038 - learning_rate: 7.5000e-05
Epoch 62/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 999ms/step - loss: 0.0028
Epoch 62: val_loss did not improve from 0.00351

Epoch 62: ReduceLROnPlateau reducing learning rate to 3.7500001781154424e-05.
126/126 ━━━━━━━━━━━━━━━━━━━━ 136s 1s/step - loss: 0.0028 - val_loss: 0.0036 - learning_rate: 7.5000e-05
Epoch 63/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 859ms/step - loss: 0.0027
Epoch 63: val_loss did not improve from 0.00351
126/126 ━━━━━━━━━━━━━━━━━━━━ 114s 912ms/step - loss: 0.0028 - val_loss: 0.0036 - learning_rate: 3.7500e-05
Epoch 64/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 808ms/step - loss: 0.0027
Epoch 64: val_loss did not improve from 0.00351
126/126 ━━━━━━━━━━━━━━━━━━━━ 109s 866ms/step - loss: 0.0028 - val_loss: 0.0036 - learning_rate: 3.7500e-05
Epoch 65/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 787ms/step - loss: 0.0027
Epoch 65: val_loss did not improve from 0.00351
126/126 ━━━━━━━━━━━━━━━━━━━━ 106s 838ms/step - loss: 0.0027 - val_loss: 0.0040 - learning_rate: 3.7500e-05
Epoch 66/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 772ms/step - loss: 0.0027
Epoch 66: val_loss did not improve from 0.00351
126/126 ━━━━━━━━━━━━━━━━━━━━ 104s 829ms/step - loss: 0.0027 - val_loss: 0.0038 - learning_rate: 3.7500e-05
Epoch 67/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 749ms/step - loss: 0.0027
Epoch 67: val_loss did not improve from 0.00351
126/126 ━━━━━━━━━━━━━━━━━━━━ 101s 802ms/step - loss: 0.0028 - val_loss: 0.0037 - learning_rate: 3.7500e-05
Epoch 68/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 741ms/step - loss: 0.0026
Epoch 68: val_loss did not improve from 0.00351
126/126 ━━━━━━━━━━━━━━━━━━━━ 99s 787ms/step - loss: 0.0027 - val_loss: 0.0037 - learning_rate: 3.7500e-05
Epoch 69/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 739ms/step - loss: 0.0027
Epoch 69: val_loss did not improve from 0.00351
126/126 ━━━━━━━━━━━━━━━━━━━━ 100s 792ms/step - loss: 0.0028 - val_loss: 0.0037 - learning_rate: 3.7500e-05
Done station 1 | Corr=0.873 RMSE=41.19 MAE=30.37 MAPE=0.393
Epoch 1/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 750ms/step - loss: 0.1087
Epoch 1: val_loss improved from None to 0.00800, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station2_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 116s 816ms/step - loss: 0.0382 - val_loss: 0.0080 - learning_rate: 3.0000e-04
Epoch 2/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 725ms/step - loss: 0.0100
Epoch 2: val_loss improved from 0.00800 to 0.00681, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station2_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 98s 780ms/step - loss: 0.0095 - val_loss: 0.0068 - learning_rate: 3.0000e-04
Epoch 3/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 718ms/step - loss: 0.0085
Epoch 3: val_loss improved from 0.00681 to 0.00606, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station2_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 96s 764ms/step - loss: 0.0084 - val_loss: 0.0061 - learning_rate: 3.0000e-04
Epoch 4/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 708ms/step - loss: 0.0084
Epoch 4: val_loss improved from 0.00606 to 0.00581, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station2_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 97s 770ms/step - loss: 0.0082 - val_loss: 0.0058 - learning_rate: 3.0000e-04
Epoch 5/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 695ms/step - loss: 0.0076
Epoch 5: val_loss improved from 0.00581 to 0.00556, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station2_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 94s 744ms/step - loss: 0.0074 - val_loss: 0.0056 - learning_rate: 3.0000e-04
Epoch 6/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 700ms/step - loss: 0.0073
Epoch 6: val_loss improved from 0.00556 to 0.00539, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station2_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 95s 754ms/step - loss: 0.0071 - val_loss: 0.0054 - learning_rate: 3.0000e-04
Epoch 7/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 699ms/step - loss: 0.0069
Epoch 7: val_loss improved from 0.00539 to 0.00440, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station2_best.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 95s 758ms/step - loss: 0.0066 - val_loss: 0.0044 - learning_rate: 3.0000e-04
Epoch 8/200

In [10]:
results_station_df = pd.DataFrame(all_results).sort_values("Station_No").reset_index(drop=True)
results_station_df

   Station_No  n_test  Correlation       RMSE      MAPE        MAE
0           1    1691     0.872754  41.191441  0.393175  30.371610
1           2    1691     0.864578  24.427860  0.129134  15.843320
2           3    1691     0.852400  35.470944  0.351853  24.578048
3           4    1691     0.876883  40.403712  0.169781  28.341695
4           5    1691     0.943195  21.396153  3.996790  15.906768
5           6    1689     0.899586  24.734059  0.127421  16.493991

In [18]:
print("Station-wise results:")
display(results_station_df)

print("\nMean across stations:")
print(results_station_df[["Correlation","RMSE","MAE","MAPE"]].mean())

Station-wise results:

   Station_No  n_test  Correlation       RMSE      MAPE        MAE
0           1    1691     0.872754  41.191441  0.393175  30.371610
1           2    1691     0.864578  24.427860  0.129134  15.843320
2           3    1691     0.852400  35.470944  0.351853  24.578048
3           4    1691     0.876883  40.403712  0.169781  28.341695
4           5    1691     0.943195  21.396153  3.996790  15.906768
5           6    1689     0.899586  24.734059  0.127421  16.493991

Mean across stations:
Correlation     0.884899
RMSE           31.270695
MAE            21.922572
MAPE            0.861359
dtype: float64

In [12]:
print("MAPE median:", results_station_df["MAPE"].median())

MAPE median: 0.2608167583120065

In [23]:
import importlib
import joblib
from datetime import timedelta
import models.cnn_bilstm as cnn_bilstm

importlib.reload(cnn_bilstm)

In [24]:
from models.cnn_bilstm import train_cnn_bilstm_v2

In [26]:
print("Station 1 check - X_train shape:", X_train.shape, "y_train shape:", y_train.shape)

Station 1 check - X_train shape: (8112, 32) y_train shape: (8112,)

In [30]:
# ==== OPTIMAL CONFIG FOUND FROM GRID ====
SEQ_LEN = 48
EPOCHS = 200
BATCH = 64
PATIENCE = 20
LSTM_UNITS = 128
LR = 3e-4

all_results = []

for st_dir in station_dirs:
    st = int(st_dir.name.split("_")[1])

    train_df = pd.read_csv(st_dir / "train.csv")
    val_df   = pd.read_csv(st_dir / "val.csv")
    test_df  = pd.read_csv(st_dir / "test.csv")

    feature_cols = [c for c in train_df.columns if c not in id_cols + [target_col]]

    X_train = train_df[feature_cols].values.astype(np.float32)
    y_train = train_df[target_col].values.astype(np.float32)

    X_val = val_df[feature_cols].values.astype(np.float32)
    y_val = val_df[target_col].values.astype(np.float32)

    X_test = test_df[feature_cols].values.astype(np.float32)
    y_test = test_df[target_col].values.astype(np.float32)

    ckpt = ARTIFACTS_DIR / f"cnn_bilstm_station{st}_opt.keras"

    model, _ = train_cnn_bilstm(
        X_train, y_train,
        X_val, y_val,
        seq_len=SEQ_LEN,
        epochs=EPOCHS,
        batch_size=BATCH,
        use_early_stopping=True,
        patience=PATIENCE,
        learning_rate=LR,
        lstm_units=LSTM_UNITS,
        use_attention=True,
        checkpoint_path=str(ckpt)
    )

    best = load_model(ckpt)

    y_pred = predict_cnn_bilstm(best, X_test, seq_len=SEQ_LEN)
    y_true = y_test[SEQ_LEN:]

    m = compute_metrics_real_scale(
        y_true_scaled=y_true,
        y_pred_scaled=y_pred,
        scaler=pm25_scaler,
        eps=1.0,
        mask_nan=True
    )

    row = {"Station_No": st}
    row.update(m)
    all_results.append(row)

    print(f"Station {st} | Corr={m['Correlation']:.3f} RMSE={m['RMSE']:.2f}")

results_opt = pd.DataFrame(all_results)
print("\nMean across stations:")
print(results_opt[["Correlation","RMSE","MAE","MAPE"]].mean())

Epoch 1/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - loss: 0.1227
Epoch 1: val_loss improved from None to 0.01189, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 191ms/step - loss: 0.0471 - val_loss: 0.0119 - learning_rate: 3.0000e-04
Epoch 2/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 288ms/step - loss: 0.0140
Epoch 2: val_loss improved from 0.01189 to 0.01133, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 39s 310ms/step - loss: 0.0130 - val_loss: 0.0113 - learning_rate: 3.0000e-04
Epoch 3/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 323ms/step - loss: 0.0126
Epoch 3: val_loss did not improve from 0.01133
126/126 ━━━━━━━━━━━━━━━━━━━━ 45s 343ms/step - loss: 0.0120 - val_loss: 0.0119 - learning_rate: 3.0000e-04
Epoch 4/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 257ms/step - loss: 0.0114
Epoch 4: val_loss improved from 0.01133 to 0.01107, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 35s 279ms/step - loss: 0.0112 - val_loss: 0.0111 - learning_rate: 3.0000e-04
Epoch 5/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 268ms/step - loss: 0.0107
Epoch 5: val_loss improved from 0.01107 to 0.01096, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 37s 290ms/step - loss: 0.0107 - val_loss: 0.0110 - learning_rate: 3.0000e-04
Epoch 6/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 276ms/step - loss: 0.0099
Epoch 6: val_loss improved from 0.01096 to 0.01084, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 37s 296ms/step - loss: 0.0097 - val_loss: 0.0108 - learning_rate: 3.0000e-04
Epoch 7/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 277ms/step - loss: 0.0089
Epoch 7: val_loss improved from 0.01084 to 0.00872, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 38s 302ms/step - loss: 0.0085 - val_loss: 0.0087 - learning_rate: 3.0000e-04
Epoch 8/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 329ms/step - loss: 0.0077
Epoch 8: val_loss improved from 0.00872 to 0.00645, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 48s 352ms/step - loss: 0.0075 - val_loss: 0.0065 - learning_rate: 3.0000e-04
Epoch 9/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 289ms/step - loss: 0.0067
Epoch 9: val_loss improved from 0.00645 to 0.00629, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 39s 310ms/step - loss: 0.0068 - val_loss: 0.0063 - learning_rate: 3.0000e-04
Epoch 10/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 256ms/step - loss: 0.0065
Epoch 10: val_loss improved from 0.00629 to 0.00566, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 37s 277ms/step - loss: 0.0065 - val_loss: 0.0057 - learning_rate: 3.0000e-04
Epoch 11/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 354ms/step - loss: 0.0061
Epoch 11: val_loss did not improve from 0.00566
126/126 ━━━━━━━━━━━━━━━━━━━━ 53s 373ms/step - loss: 0.0060 - val_loss: 0.0057 - learning_rate: 3.0000e-04
Epoch 12/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 325ms/step - loss: 0.0057
Epoch 12: val_loss did not improve from 0.00566
126/126 ━━━━━━━━━━━━━━━━━━━━ 43s 345ms/step - loss: 0.0057 - val_loss: 0.0068 - learning_rate: 3.0000e-04
Epoch 13/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 287ms/step - loss: 0.0056
Epoch 13: val_loss improved from 0.00566 to 0.00499, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 77s 308ms/step - loss: 0.0056 - val_loss: 0.0050 - learning_rate: 3.0000e-04
Epoch 14/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 306ms/step - loss: 0.0052
Epoch 14: val_loss improved from 0.00499 to 0.00499, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 42s 331ms/step - loss: 0.0052 - val_loss: 0.0050 - learning_rate: 3.0000e-04
Epoch 15/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 331ms/step - loss: 0.0052
Epoch 15: val_loss improved from 0.00499 to 0.00484, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 44s 353ms/step - loss: 0.0050 - val_loss: 0.0048 - learning_rate: 3.0000e-04
Epoch 16/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 287ms/step - loss: 0.0049
Epoch 16: val_loss did not improve from 0.00484
126/126 ━━━━━━━━━━━━━━━━━━━━ 38s 305ms/step - loss: 0.0049 - val_loss: 0.0049 - learning_rate: 3.0000e-04
Epoch 17/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 291ms/step - loss: 0.0048
Epoch 17: val_loss improved from 0.00484 to 0.00482, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 40s 315ms/step - loss: 0.0048 - val_loss: 0.0048 - learning_rate: 3.0000e-04
Epoch 18/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 275ms/step - loss: 0.0043
Epoch 18: val_loss improved from 0.00482 to 0.00439, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 38s 298ms/step - loss: 0.0045 - val_loss: 0.0044 - learning_rate: 3.0000e-04
Epoch 19/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 284ms/step - loss: 0.0044
Epoch 19: val_loss did not improve from 0.00439
126/126 ━━━━━━━━━━━━━━━━━━━━ 38s 305ms/step - loss: 0.0045 - val_loss: 0.0044 - learning_rate: 3.0000e-04
Epoch 20/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 279ms/step - loss: 0.0047
Epoch 20: val_loss did not improve from 0.00439
126/126 ━━━━━━━━━━━━━━━━━━━━ 40s 300ms/step - loss: 0.0046 - val_loss: 0.0059 - learning_rate: 3.0000e-04
Epoch 21/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 321ms/step - loss: 0.0043
Epoch 21: val_loss improved from 0.00439 to 0.00431, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 45s 360ms/step - loss: 0.0044 - val_loss: 0.0043 - learning_rate: 3.0000e-04
Epoch 22/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 258ms/step - loss: 0.0041
Epoch 22: val_loss did not improve from 0.00431
126/126 ━━━━━━━━━━━━━━━━━━━━ 35s 277ms/step - loss: 0.0042 - val_loss: 0.0043 - learning_rate: 3.0000e-04
Epoch 23/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 227ms/step - loss: 0.0043
Epoch 23: val_loss did not improve from 0.00431
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 246ms/step - loss: 0.0041 - val_loss: 0.0044 - learning_rate: 3.0000e-04
Epoch 24/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 222ms/step - loss: 0.0040
Epoch 24: val_loss improved from 0.00431 to 0.00420, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 243ms/step - loss: 0.0039 - val_loss: 0.0042 - learning_rate: 3.0000e-04
Epoch 25/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 227ms/step - loss: 0.0040
Epoch 25: val_loss did not improve from 0.00420
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 245ms/step - loss: 0.0041 - val_loss: 0.0042 - learning_rate: 3.0000e-04
Epoch 26/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 243ms/step - loss: 0.0039
Epoch 26: val_loss improved from 0.00420 to 0.00410, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 43s 263ms/step - loss: 0.0040 - val_loss: 0.0041 - learning_rate: 3.0000e-04
Epoch 27/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 236ms/step - loss: 0.0038
Epoch 27: val_loss did not improve from 0.00410
126/126 ━━━━━━━━━━━━━━━━━━━━ 32s 254ms/step - loss: 0.0040 - val_loss: 0.0043 - learning_rate: 3.0000e-04
Epoch 28/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 236ms/step - loss: 0.0040
Epoch 28: val_loss did not improve from 0.00410
126/126 ━━━━━━━━━━━━━━━━━━━━ 32s 255ms/step - loss: 0.0038 - val_loss: 0.0041 - learning_rate: 3.0000e-04
Epoch 29/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 234ms/step - loss: 0.0039
Epoch 29: val_loss improved from 0.00410 to 0.00387, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 32s 254ms/step - loss: 0.0039 - val_loss: 0.0039 - learning_rate: 3.0000e-04
Epoch 30/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 233ms/step - loss: 0.0037
Epoch 30: val_loss did not improve from 0.00387
126/126 ━━━━━━━━━━━━━━━━━━━━ 32s 251ms/step - loss: 0.0036 - val_loss: 0.0046 - learning_rate: 3.0000e-04
Epoch 31/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 238ms/step - loss: 0.0038
Epoch 31: val_loss improved from 0.00387 to 0.00385, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 33s 258ms/step - loss: 0.0037 - val_loss: 0.0038 - learning_rate: 3.0000e-04
Epoch 32/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 229ms/step - loss: 0.0036
Epoch 32: val_loss did not improve from 0.00385
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 247ms/step - loss: 0.0035 - val_loss: 0.0040 - learning_rate: 3.0000e-04
Epoch 33/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 227ms/step - loss: 0.0038
Epoch 33: val_loss did not improve from 0.00385
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 246ms/step - loss: 0.0036 - val_loss: 0.0039 - learning_rate: 3.0000e-04
Epoch 34/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 227ms/step - loss: 0.0035
Epoch 34: val_loss did not improve from 0.00385
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 247ms/step - loss: 0.0036 - val_loss: 0.0054 - learning_rate: 3.0000e-04
Epoch 35/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 229ms/step - loss: 0.0038
Epoch 35: val_loss improved from 0.00385 to 0.00384, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 32s 250ms/step - loss: 0.0035 - val_loss: 0.0038 - learning_rate: 3.0000e-04
Epoch 36/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 230ms/step - loss: 0.0033
Epoch 36: val_loss did not improve from 0.00384
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 248ms/step - loss: 0.0034 - val_loss: 0.0041 - learning_rate: 3.0000e-04
Epoch 37/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 225ms/step - loss: 0.0033
Epoch 37: val_loss improved from 0.00384 to 0.00384, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 245ms/step - loss: 0.0034 - val_loss: 0.0038 - learning_rate: 3.0000e-04
Epoch 38/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 229ms/step - loss: 0.0035
Epoch 38: val_loss did not improve from 0.00384
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 250ms/step - loss: 0.0034 - val_loss: 0.0040 - learning_rate: 3.0000e-04
Epoch 39/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 233ms/step - loss: 0.0033
Epoch 39: val_loss did not improve from 0.00384

Epoch 39: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.
126/126 ━━━━━━━━━━━━━━━━━━━━ 33s 258ms/step - loss: 0.0034 - val_loss: 0.0043 - learning_rate: 3.0000e-04
Epoch 40/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 231ms/step - loss: 0.0032
Epoch 40: val_loss improved from 0.00384 to 0.00376, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 33s 261ms/step - loss: 0.0032 - val_loss: 0.0038 - learning_rate: 1.5000e-04
Epoch 41/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 270ms/step - loss: 0.0030
Epoch 41: val_loss improved from 0.00376 to 0.00365, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 37s 291ms/step - loss: 0.0031 - val_loss: 0.0037 - learning_rate: 1.5000e-04
Epoch 42/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 281ms/step - loss: 0.0030
Epoch 42: val_loss improved from 0.00365 to 0.00362, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 40s 317ms/step - loss: 0.0031 - val_loss: 0.0036 - learning_rate: 1.5000e-04
Epoch 43/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 266ms/step - loss: 0.0031
Epoch 43: val_loss did not improve from 0.00362
126/126 ━━━━━━━━━━━━━━━━━━━━ 36s 284ms/step - loss: 0.0031 - val_loss: 0.0038 - learning_rate: 1.5000e-04
Epoch 44/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 229ms/step - loss: 0.0030
Epoch 44: val_loss did not improve from 0.00362
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 248ms/step - loss: 0.0031 - val_loss: 0.0037 - learning_rate: 1.5000e-04
Epoch 45/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 229ms/step - loss: 0.0032
Epoch 45: val_loss did not improve from 0.00362
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 248ms/step - loss: 0.0030 - val_loss: 0.0037 - learning_rate: 1.5000e-04
Epoch 46/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 236ms/step - loss: 0.0030
Epoch 46: val_loss did not improve from 0.00362
126/126 ━━━━━━━━━━━━━━━━━━━━ 33s 258ms/step - loss: 0.0030 - val_loss: 0.0036 - learning_rate: 1.5000e-04
Epoch 47/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 219ms/step - loss: 0.0028
Epoch 47: val_loss did not improve from 0.00362
126/126 ━━━━━━━━━━━━━━━━━━━━ 38s 237ms/step - loss: 0.0030 - val_loss: 0.0037 - learning_rate: 1.5000e-04
Epoch 48/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 230ms/step - loss: 0.0031
Epoch 48: val_loss did not improve from 0.00362
126/126 ━━━━━━━━━━━━━━━━━━━━ 32s 250ms/step - loss: 0.0030 - val_loss: 0.0037 - learning_rate: 1.5000e-04
Epoch 49/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 231ms/step - loss: 0.0030
Epoch 49: val_loss did not improve from 0.00362
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 249ms/step - loss: 0.0030 - val_loss: 0.0036 - learning_rate: 1.5000e-04
Epoch 50/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 230ms/step - loss: 0.0028
Epoch 50: val_loss did not improve from 0.00362
126/126 ━━━━━━━━━━━━━━━━━━━━ 32s 250ms/step - loss: 0.0029 - val_loss: 0.0041 - learning_rate: 1.5000e-04
Epoch 51/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 231ms/step - loss: 0.0030
Epoch 51: val_loss did not improve from 0.00362

Epoch 51: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
126/126 ━━━━━━━━━━━━━━━━━━━━ 32s 250ms/step - loss: 0.0030 - val_loss: 0.0038 - learning_rate: 1.5000e-04
Epoch 52/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 230ms/step - loss: 0.0027
Epoch 52: val_loss did not improve from 0.00362
126/126 ━━━━━━━━━━━━━━━━━━━━ 32s 250ms/step - loss: 0.0028 - val_loss: 0.0036 - learning_rate: 7.5000e-05
Epoch 53/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 225ms/step - loss: 0.0027
Epoch 53: val_loss did not improve from 0.00362
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 243ms/step - loss: 0.0028 - val_loss: 0.0036 - learning_rate: 7.5000e-05
Epoch 54/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 231ms/step - loss: 0.0029
Epoch 54: val_loss did not improve from 0.00362
126/126 ━━━━━━━━━━━━━━━━━━━━ 32s 251ms/step - loss: 0.0028 - val_loss: 0.0037 - learning_rate: 7.5000e-05
Epoch 55/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 231ms/step - loss: 0.0028
Epoch 55: val_loss did not improve from 0.00362
126/126 ━━━━━━━━━━━━━━━━━━━━ 32s 250ms/step - loss: 0.0028 - val_loss: 0.0038 - learning_rate: 7.5000e-05
Epoch 56/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 230ms/step - loss: 0.0029
Epoch 56: val_loss did not improve from 0.00362
126/126 ━━━━━━━━━━━━━━━━━━━━ 32s 250ms/step - loss: 0.0028 - val_loss: 0.0036 - learning_rate: 7.5000e-05
Epoch 57/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 227ms/step - loss: 0.0028
Epoch 57: val_loss did not improve from 0.00362
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 246ms/step - loss: 0.0028 - val_loss: 0.0037 - learning_rate: 7.5000e-05
Epoch 58/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 233ms/step - loss: 0.0027
Epoch 58: val_loss did not improve from 0.00362
126/126 ━━━━━━━━━━━━━━━━━━━━ 32s 254ms/step - loss: 0.0028 - val_loss: 0.0037 - learning_rate: 7.5000e-05
Epoch 59/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 233ms/step - loss: 0.0027
Epoch 59: val_loss did not improve from 0.00362
126/126 ━━━━━━━━━━━━━━━━━━━━ 32s 252ms/step - loss: 0.0028 - val_loss: 0.0039 - learning_rate: 7.5000e-05
Epoch 60/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 226ms/step - loss: 0.0027
Epoch 60: val_loss improved from 0.00362 to 0.00358, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 248ms/step - loss: 0.0028 - val_loss: 0.0036 - learning_rate: 7.5000e-05
Epoch 61/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 230ms/step - loss: 0.0028
Epoch 61: val_loss did not improve from 0.00358

Epoch 61: ReduceLROnPlateau reducing learning rate to 3.7500001781154424e-05.
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 249ms/step - loss: 0.0028 - val_loss: 0.0037 - learning_rate: 7.5000e-05
Epoch 62/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 227ms/step - loss: 0.0026
Epoch 62: val_loss did not improve from 0.00358
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 245ms/step - loss: 0.0027 - val_loss: 0.0036 - learning_rate: 3.7500e-05
Epoch 63/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 227ms/step - loss: 0.0027
Epoch 63: val_loss did not improve from 0.00358
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 248ms/step - loss: 0.0027 - val_loss: 0.0036 - learning_rate: 3.7500e-05
Epoch 64/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 227ms/step - loss: 0.0027
Epoch 64: val_loss did not improve from 0.00358
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 245ms/step - loss: 0.0026 - val_loss: 0.0036 - learning_rate: 3.7500e-05
Epoch 65/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 230ms/step - loss: 0.0027
Epoch 65: val_loss did not improve from 0.00358
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 249ms/step - loss: 0.0027 - val_loss: 0.0038 - learning_rate: 3.7500e-05
Epoch 66/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 229ms/step - loss: 0.0027
Epoch 66: val_loss did not improve from 0.00358
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 249ms/step - loss: 0.0027 - val_loss: 0.0036 - learning_rate: 3.7500e-05
Epoch 67/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 234ms/step - loss: 0.0025
Epoch 67: val_loss improved from 0.00358 to 0.00357, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_opt.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 32s 254ms/step - loss: 0.0026 - val_loss: 0.0036 - learning_rate: 3.7500e-05
Epoch 68/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 226ms/step - loss: 0.0026
Epoch 68: val_loss did not improve from 0.00357
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 245ms/step - loss: 0.0027 - val_loss: 0.0037 - learning_rate: 3.7500e-05
Epoch 69/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 231ms/step - loss: 0.0025
Epoch 69: val_loss did not improve from 0.00357
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 249ms/step - loss: 0.0026 - val_loss: 0.0037 - learning_rate: 3.7500e-05
Epoch 70/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 233ms/step - loss: 0.0027
Epoch 70: val_loss did not improve from 0.00357
126/126 ━━━━━━━━━━━━━━━━━━━━ 32s 252ms/step - loss: 0.0026 - val_loss: 0.0036 - learning_rate: 3.7500e-05
Epoch 71/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 228ms/step - loss: 0.0025
Epoch 71: val_loss did not improve from 0.00357

Epoch 71: ReduceLROnPlateau reducing learning rate to 1.8750000890577212e-05.
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 246ms/step - loss: 0.0027 - val_loss: 0.0036 - learning_rate: 3.7500e-05
Epoch 72/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 228ms/step - loss: 0.0028
Epoch 72: val_loss did not improve from 0.00357
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 249ms/step - loss: 0.0026 - val_loss: 0.0036 - learning_rate: 1.8750e-05
Epoch 73/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 227ms/step - loss: 0.0027
Epoch 73: val_loss did not improve from 0.00357
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 247ms/step - loss: 0.0026 - val_loss: 0.0036 - learning_rate: 1.8750e-05
Epoch 74/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 224ms/step - loss: 0.0026
Epoch 74: val_loss did not improve from 0.00357
126/126 ━━━━━━━━━━━━━━━━━━━━ 31s 244ms/step - loss: 0.0026 - val_loss: 0.0036 - learning_rate: 1.8750e-05
Epoch 75/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 233ms/step - loss: 0.0026
Epoch 75: val_loss did not improve from 0.00357

In [31]:
results_opt = pd.DataFrame(all_results)
print("\nMean across stations:")
print(results_opt[["Correlation","RMSE","MAE","MAPE"]].mean())

Mean across stations:
Correlation     0.885042
RMSE           31.178803
MAE            21.682525
MAPE            0.866492
dtype: float64

In [32]:
import numpy as np
from models.cnn_bilstm import train_cnn_bilstm, predict_cnn_bilstm

# =============================
# 1) Convert target to REAL scale
# =============================
# y_train, y_val, y_test hiện đang là scaled
# Ta inverse để về PM2.5 thật

y_train_real = pm25_scaler.inverse_transform(y_train.reshape(-1,1)).ravel()
y_val_real   = pm25_scaler.inverse_transform(y_val.reshape(-1,1)).ravel()
y_test_real  = pm25_scaler.inverse_transform(y_test.reshape(-1,1)).ravel()

# =============================
# 2) Log-transform
# =============================
y_train_log = np.log1p(y_train_real)
y_val_log   = np.log1p(y_val_real)
y_test_log  = np.log1p(y_test_real)

# =============================
# 3) Train model on log target
# =============================
SEQ_LEN = 48
EPOCHS = 200
BATCH = 64

ckpt_log = ARTIFACTS_DIR / "cnn_bilstm_station1_log.keras"

model_log, _ = train_cnn_bilstm(
    X_train, y_train_log,
    X_val, y_val_log,
    seq_len=SEQ_LEN,
    epochs=EPOCHS,
    batch_size=BATCH,
    use_early_stopping=True,
    patience=20,
    learning_rate=3e-4,
    lstm_units=128,
    use_attention=True,
    checkpoint_path=str(ckpt_log)
)

best_log = load_model(ckpt_log)

# =============================
# 4) Predict (log space)
# =============================
y_pred_log = predict_cnn_bilstm(best_log, X_test, seq_len=SEQ_LEN)
y_true_log = y_test_log[SEQ_LEN:]

# =============================
# 5) Convert back to REAL
# =============================
y_pred_real = np.expm1(y_pred_log)
y_true_real = np.expm1(y_true_log)

# =============================
# 6) Compute metrics manually
# =============================
diff = y_pred_real - y_true_real

rmse = np.sqrt(np.mean(diff**2))
mae = np.mean(np.abs(diff))
corr = np.corrcoef(y_pred_real, y_true_real)[0,1]

mask = np.abs(y_true_real) >= 1.0
mape = np.mean(np.abs(diff[mask]) / np.abs(y_true_real[mask]))

print("\nStation 1 - LOG MODEL REAL SCALE:")
print("Correlation:", corr)
print("RMSE:", rmse)
print("MAE:", mae)
print("MAPE:", mape)

Epoch 1/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 523ms/step - loss: 0.5633
Epoch 1: val_loss improved from None to 0.07900, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_log.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 88s 580ms/step - loss: 0.2520 - val_loss: 0.0790 - learning_rate: 3.0000e-04
Epoch 2/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 891ms/step - loss: 0.1260
Epoch 2: val_loss improved from 0.07900 to 0.04621, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_log.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 121s 960ms/step - loss: 0.1208 - val_loss: 0.0462 - learning_rate: 3.0000e-04
Epoch 3/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.1142
Epoch 3: val_loss did not improve from 0.04621
126/126 ━━━━━━━━━━━━━━━━━━━━ 160s 1s/step - loss: 0.1113 - val_loss: 0.0763 - learning_rate: 3.0000e-04
Epoch 4/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.1076
Epoch 4: val_loss improved from 0.04621 to 0.03469, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_log.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 167s 1s/step - loss: 0.1031 - val_loss: 0.0347 - learning_rate: 3.0000e-04
Epoch 5/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0979
Epoch 5: val_loss improved from 0.03469 to 0.03364, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_log.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 171s 1s/step - loss: 0.0962 - val_loss: 0.0336 - learning_rate: 3.0000e-04
Epoch 6/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0965
Epoch 6: val_loss did not improve from 0.03364
126/126 ━━━━━━━━━━━━━━━━━━━━ 188s 1s/step - loss: 0.0941 - val_loss: 0.0388 - learning_rate: 3.0000e-04
Epoch 7/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0951
Epoch 7: val_loss improved from 0.03364 to 0.02489, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_log.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 203s 2s/step - loss: 0.0911 - val_loss: 0.0249 - learning_rate: 3.0000e-04
Epoch 8/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 2s/step - loss: 0.0904
Epoch 8: val_loss improved from 0.02489 to 0.02258, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_log.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 211s 2s/step - loss: 0.0899 - val_loss: 0.0226 - learning_rate: 3.0000e-04
Epoch 9/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 2s/step - loss: 0.0879
Epoch 9: val_loss did not improve from 0.02258
126/126 ━━━━━━━━━━━━━━━━━━━━ 230s 2s/step - loss: 0.0887 - val_loss: 0.0301 - learning_rate: 3.0000e-04
Epoch 10/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 2s/step - loss: 0.0884
Epoch 10: val_loss did not improve from 0.02258
126/126 ━━━━━━━━━━━━━━━━━━━━ 238s 2s/step - loss: 0.0878 - val_loss: 0.0232 - learning_rate: 3.0000e-04
Epoch 11/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 2s/step - loss: 0.0872
Epoch 11: val_loss did not improve from 0.02258
126/126 ━━━━━━━━━━━━━━━━━━━━ 278s 2s/step - loss: 0.0843 - val_loss: 0.0238 - learning_rate: 3.0000e-04
Epoch 12/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 2s/step - loss: 0.0849
Epoch 12: val_loss improved from 0.02258 to 0.02047, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_log.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 295s 2s/step - loss: 0.0855 - val_loss: 0.0205 - learning_rate: 3.0000e-04
Epoch 13/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 2s/step - loss: 0.0831
Epoch 13: val_loss did not improve from 0.02047
126/126 ━━━━━━━━━━━━━━━━━━━━ 324s 3s/step - loss: 0.0837 - val_loss: 0.0237 - learning_rate: 3.0000e-04
Epoch 14/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 3s/step - loss: 0.0829
Epoch 14: val_loss did not improve from 0.02047
126/126 ━━━━━━━━━━━━━━━━━━━━ 382s 3s/step - loss: 0.0818 - val_loss: 0.0220 - learning_rate: 3.0000e-04
Epoch 15/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 3s/step - loss: 0.0803
Epoch 15: val_loss did not improve from 0.02047
126/126 ━━━━━━━━━━━━━━━━━━━━ 381s 3s/step - loss: 0.0814 - val_loss: 0.0267 - learning_rate: 3.0000e-04
Epoch 16/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 3s/step - loss: 0.0804
Epoch 16: val_loss did not improve from 0.02047
126/126 ━━━━━━━━━━━━━━━━━━━━ 355s 3s/step - loss: 0.0790 - val_loss: 0.0267 - learning_rate: 3.0000e-04
Epoch 17/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 3s/step - loss: 0.0792
Epoch 17: val_loss improved from 0.02047 to 0.01942, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_log.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 418s 3s/step - loss: 0.0806 - val_loss: 0.0194 - learning_rate: 3.0000e-04
Epoch 18/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 3s/step - loss: 0.0830
Epoch 18: val_loss did not improve from 0.01942
126/126 ━━━━━━━━━━━━━━━━━━━━ 422s 3s/step - loss: 0.0823 - val_loss: 0.0252 - learning_rate: 3.0000e-04
Epoch 19/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 3s/step - loss: 0.0768
Epoch 19: val_loss improved from 0.01942 to 0.01632, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_log.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 399s 3s/step - loss: 0.0785 - val_loss: 0.0163 - learning_rate: 3.0000e-04
Epoch 20/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 3s/step - loss: 0.0798
Epoch 20: val_loss did not improve from 0.01632
126/126 ━━━━━━━━━━━━━━━━━━━━ 431s 3s/step - loss: 0.0791 - val_loss: 0.0254 - learning_rate: 3.0000e-04
Epoch 21/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 3s/step - loss: 0.0795
Epoch 21: val_loss did not improve from 0.01632
126/126 ━━━━━━━━━━━━━━━━━━━━ 431s 3s/step - loss: 0.0784 - val_loss: 0.0196 - learning_rate: 3.0000e-04
Epoch 22/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 3s/step - loss: 0.0753
Epoch 22: val_loss did not improve from 0.01632
126/126 ━━━━━━━━━━━━━━━━━━━━ 380s 3s/step - loss: 0.0781 - val_loss: 0.0178 - learning_rate: 3.0000e-04
Epoch 23/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 3s/step - loss: 0.0765
Epoch 23: val_loss improved from 0.01632 to 0.01595, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_log.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 375s 3s/step - loss: 0.0757 - val_loss: 0.0159 - learning_rate: 3.0000e-04
Epoch 24/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0755
Epoch 24: val_loss did not improve from 0.01595
126/126 ━━━━━━━━━━━━━━━━━━━━ 184s 1s/step - loss: 0.0766 - val_loss: 0.0239 - learning_rate: 3.0000e-04
Epoch 25/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0776
Epoch 25: val_loss did not improve from 0.01595
126/126 ━━━━━━━━━━━━━━━━━━━━ 164s 1s/step - loss: 0.0753 - val_loss: 0.0173 - learning_rate: 3.0000e-04
Epoch 26/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0718
Epoch 26: val_loss did not improve from 0.01595
126/126 ━━━━━━━━━━━━━━━━━━━━ 134s 1s/step - loss: 0.0729 - val_loss: 0.0163 - learning_rate: 3.0000e-04
Epoch 27/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 941ms/step - loss: 0.0770
Epoch 27: val_loss did not improve from 0.01595
126/126 ━━━━━━━━━━━━━━━━━━━━ 126s 999ms/step - loss: 0.0760 - val_loss: 0.0182 - learning_rate: 3.0000e-04
Epoch 28/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 869ms/step - loss: 0.0777
Epoch 28: val_loss did not improve from 0.01595
126/126 ━━━━━━━━━━━━━━━━━━━━ 117s 927ms/step - loss: 0.0753 - val_loss: 0.0161 - learning_rate: 3.0000e-04
Epoch 29/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 845ms/step - loss: 0.0704
Epoch 29: val_loss improved from 0.01595 to 0.01545, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_log.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 113s 901ms/step - loss: 0.0734 - val_loss: 0.0154 - learning_rate: 3.0000e-04
Epoch 30/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 852ms/step - loss: 0.0726
Epoch 30: val_loss improved from 0.01545 to 0.01466, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_log.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 114s 910ms/step - loss: 0.0743 - val_loss: 0.0147 - learning_rate: 3.0000e-04
Epoch 31/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 842ms/step - loss: 0.0735
Epoch 31: val_loss did not improve from 0.01466
126/126 ━━━━━━━━━━━━━━━━━━━━ 113s 900ms/step - loss: 0.0721 - val_loss: 0.0159 - learning_rate: 3.0000e-04
Epoch 32/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 762ms/step - loss: 0.0699
Epoch 32: val_loss did not improve from 0.01466
126/126 ━━━━━━━━━━━━━━━━━━━━ 103s 818ms/step - loss: 0.0711 - val_loss: 0.0159 - learning_rate: 3.0000e-04
Epoch 33/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 806ms/step - loss: 0.0718
Epoch 33: val_loss improved from 0.01466 to 0.01404, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_log.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 110s 875ms/step - loss: 0.0707 - val_loss: 0.0140 - learning_rate: 3.0000e-04
Epoch 34/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 734ms/step - loss: 0.0713
Epoch 34: val_loss did not improve from 0.01404
126/126 ━━━━━━━━━━━━━━━━━━━━ 100s 795ms/step - loss: 0.0727 - val_loss: 0.0180 - learning_rate: 3.0000e-04
Epoch 35/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 817ms/step - loss: 0.0742
Epoch 35: val_loss did not improve from 0.01404
126/126 ━━━━━━━━━━━━━━━━━━━━ 110s 874ms/step - loss: 0.0736 - val_loss: 0.0171 - learning_rate: 3.0000e-04
Epoch 36/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 770ms/step - loss: 0.0692
Epoch 36: val_loss did not improve from 0.01404
126/126 ━━━━━━━━━━━━━━━━━━━━ 104s 827ms/step - loss: 0.0701 - val_loss: 0.0169 - learning_rate: 3.0000e-04
Epoch 37/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 995ms/step - loss: 0.0697
Epoch 37: val_loss did not improve from 0.01404
126/126 ━━━━━━━━━━━━━━━━━━━━ 133s 1s/step - loss: 0.0701 - val_loss: 0.0189 - learning_rate: 3.0000e-04
Epoch 38/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0727
Epoch 38: val_loss did not improve from 0.01404
126/126 ━━━━━━━━━━━━━━━━━━━━ 137s 1s/step - loss: 0.0720 - val_loss: 0.0195 - learning_rate: 3.0000e-04
Epoch 39/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 865ms/step - loss: 0.0712
Epoch 39: val_loss did not improve from 0.01404
126/126 ━━━━━━━━━━━━━━━━━━━━ 119s 942ms/step - loss: 0.0707 - val_loss: 0.0147 - learning_rate: 3.0000e-04
Epoch 40/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 956ms/step - loss: 0.0724
Epoch 40: val_loss did not improve from 0.01404
126/126 ━━━━━━━━━━━━━━━━━━━━ 130s 1s/step - loss: 0.0721 - val_loss: 0.0170 - learning_rate: 3.0000e-04
Epoch 41/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0712
Epoch 41: val_loss did not improve from 0.01404
126/126 ━━━━━━━━━━━━━━━━━━━━ 146s 1s/step - loss: 0.0706 - val_loss: 0.0143 - learning_rate: 3.0000e-04
Epoch 42/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0736
Epoch 42: val_loss did not improve from 0.01404
126/126 ━━━━━━━━━━━━━━━━━━━━ 142s 1s/step - loss: 0.0723 - val_loss: 0.0206 - learning_rate: 3.0000e-04
Epoch 43/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0721
Epoch 43: val_loss did not improve from 0.01404

Epoch 43: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.
126/126 ━━━━━━━━━━━━━━━━━━━━ 143s 1s/step - loss: 0.0723 - val_loss: 0.0142 - learning_rate: 3.0000e-04
Epoch 44/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 974ms/step - loss: 0.0663
Epoch 44: val_loss improved from 0.01404 to 0.01300, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_log.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 131s 1s/step - loss: 0.0673 - val_loss: 0.0130 - learning_rate: 1.5000e-04
Epoch 45/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0670
Epoch 45: val_loss did not improve from 0.01300
126/126 ━━━━━━━━━━━━━━━━━━━━ 144s 1s/step - loss: 0.0669 - val_loss: 0.0169 - learning_rate: 1.5000e-04
Epoch 46/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0669
Epoch 46: val_loss did not improve from 0.01300
126/126 ━━━━━━━━━━━━━━━━━━━━ 137s 1s/step - loss: 0.0672 - val_loss: 0.0141 - learning_rate: 1.5000e-04
Epoch 47/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0658
Epoch 47: val_loss did not improve from 0.01300
126/126 ━━━━━━━━━━━━━━━━━━━━ 143s 1s/step - loss: 0.0645 - val_loss: 0.0136 - learning_rate: 1.5000e-04
Epoch 48/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0671
Epoch 48: val_loss did not improve from 0.01300
126/126 ━━━━━━━━━━━━━━━━━━━━ 161s 1s/step - loss: 0.0662 - val_loss: 0.0153 - learning_rate: 1.5000e-04
Epoch 49/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0671
Epoch 49: val_loss did not improve from 0.01300
126/126 ━━━━━━━━━━━━━━━━━━━━ 136s 1s/step - loss: 0.0666 - val_loss: 0.0144 - learning_rate: 1.5000e-04
Epoch 50/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0678
Epoch 50: val_loss did not improve from 0.01300
126/126 ━━━━━━━━━━━━━━━━━━━━ 142s 1s/step - loss: 0.0663 - val_loss: 0.0138 - learning_rate: 1.5000e-04
Epoch 51/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0658
Epoch 51: val_loss did not improve from 0.01300
126/126 ━━━━━━━━━━━━━━━━━━━━ 140s 1s/step - loss: 0.0651 - val_loss: 0.0142 - learning_rate: 1.5000e-04
Epoch 52/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0668
Epoch 52: val_loss did not improve from 0.01300
126/126 ━━━━━━━━━━━━━━━━━━━━ 135s 1s/step - loss: 0.0657 - val_loss: 0.0153 - learning_rate: 1.5000e-04
Epoch 53/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 987ms/step - loss: 0.0648
Epoch 53: val_loss improved from 0.01300 to 0.01272, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_log.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 132s 1s/step - loss: 0.0649 - val_loss: 0.0127 - learning_rate: 1.5000e-04
Epoch 54/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0661
Epoch 54: val_loss did not improve from 0.01272
126/126 ━━━━━━━━━━━━━━━━━━━━ 147s 1s/step - loss: 0.0658 - val_loss: 0.0127 - learning_rate: 1.5000e-04
Epoch 55/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 980ms/step - loss: 0.0642
Epoch 55: val_loss did not improve from 0.01272
126/126 ━━━━━━━━━━━━━━━━━━━━ 132s 1s/step - loss: 0.0645 - val_loss: 0.0186 - learning_rate: 1.5000e-04
Epoch 56/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0651
Epoch 56: val_loss did not improve from 0.01272
126/126 ━━━━━━━━━━━━━━━━━━━━ 156s 1s/step - loss: 0.0648 - val_loss: 0.0146 - learning_rate: 1.5000e-04
Epoch 57/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0683
Epoch 57: val_loss did not improve from 0.01272
126/126 ━━━━━━━━━━━━━━━━━━━━ 144s 1s/step - loss: 0.0665 - val_loss: 0.0152 - learning_rate: 1.5000e-04
Epoch 58/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0658
Epoch 58: val_loss did not improve from 0.01272
126/126 ━━━━━━━━━━━━━━━━━━━━ 134s 1s/step - loss: 0.0653 - val_loss: 0.0140 - learning_rate: 1.5000e-04
Epoch 59/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 964ms/step - loss: 0.0632
Epoch 59: val_loss did not improve from 0.01272
126/126 ━━━━━━━━━━━━━━━━━━━━ 128s 1s/step - loss: 0.0639 - val_loss: 0.0135 - learning_rate: 1.5000e-04
Epoch 60/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 923ms/step - loss: 0.0651
Epoch 60: val_loss did not improve from 0.01272
126/126 ━━━━━━━━━━━━━━━━━━━━ 126s 999ms/step - loss: 0.0645 - val_loss: 0.0157 - learning_rate: 1.5000e-04
Epoch 61/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 917ms/step - loss: 0.0603
Epoch 61: val_loss did not improve from 0.01272
126/126 ━━━━━━━━━━━━━━━━━━━━ 125s 991ms/step - loss: 0.0620 - val_loss: 0.0133 - learning_rate: 1.5000e-04
Epoch 62/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 956ms/step - loss: 0.0636
Epoch 62: val_loss did not improve from 0.01272
126/126 ━━━━━━━━━━━━━━━━━━━━ 130s 1s/step - loss: 0.0650 - val_loss: 0.0129 - learning_rate: 1.5000e-04
Epoch 63/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0648
Epoch 63: val_loss did not improve from 0.01272

Epoch 63: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
126/126 ━━━━━━━━━━━━━━━━━━━━ 153s 1s/step - loss: 0.0642 - val_loss: 0.0142 - learning_rate: 1.5000e-04
Epoch 64/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0616
Epoch 64: val_loss improved from 0.01272 to 0.01233, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_log.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 139s 1s/step - loss: 0.0611 - val_loss: 0.0123 - learning_rate: 7.5000e-05
Epoch 65/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 999ms/step - loss: 0.0623
Epoch 65: val_loss did not improve from 0.01233
126/126 ━━━━━━━━━━━━━━━━━━━━ 135s 1s/step - loss: 0.0627 - val_loss: 0.0138 - learning_rate: 7.5000e-05
Epoch 66/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 869ms/step - loss: 0.0652
Epoch 66: val_loss did not improve from 0.01233
126/126 ━━━━━━━━━━━━━━━━━━━━ 117s 930ms/step - loss: 0.0630 - val_loss: 0.0134 - learning_rate: 7.5000e-05
Epoch 67/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 982ms/step - loss: 0.0632
Epoch 67: val_loss did not improve from 0.01233
126/126 ━━━━━━━━━━━━━━━━━━━━ 130s 1s/step - loss: 0.0635 - val_loss: 0.0124 - learning_rate: 7.5000e-05
Epoch 68/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 869ms/step - loss: 0.0617
Epoch 68: val_loss did not improve from 0.01233
126/126 ━━━━━━━━━━━━━━━━━━━━ 119s 948ms/step - loss: 0.0613 - val_loss: 0.0130 - learning_rate: 7.5000e-05
Epoch 69/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 870ms/step - loss: 0.0627
Epoch 69: val_loss did not improve from 0.01233
126/126 ━━━━━━━━━━━━━━━━━━━━ 117s 927ms/step - loss: 0.0633 - val_loss: 0.0123 - learning_rate: 7.5000e-05
Epoch 70/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 904ms/step - loss: 0.0609
Epoch 70: val_loss improved from 0.01233 to 0.01207, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_log.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 122s 967ms/step - loss: 0.0606 - val_loss: 0.0121 - learning_rate: 7.5000e-05
Epoch 71/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 891ms/step - loss: 0.0613
Epoch 71: val_loss did not improve from 0.01207
126/126 ━━━━━━━━━━━━━━━━━━━━ 118s 938ms/step - loss: 0.0616 - val_loss: 0.0122 - learning_rate: 7.5000e-05
Epoch 72/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 865ms/step - loss: 0.0617
Epoch 72: val_loss did not improve from 0.01207
126/126 ━━━━━━━━━━━━━━━━━━━━ 116s 927ms/step - loss: 0.0614 - val_loss: 0.0129 - learning_rate: 7.5000e-05
Epoch 73/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0624
Epoch 73: val_loss did not improve from 0.01207
126/126 ━━━━━━━━━━━━━━━━━━━━ 187s 1s/step - loss: 0.0626 - val_loss: 0.0131 - learning_rate: 7.5000e-05
Epoch 74/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0616
Epoch 74: val_loss did not improve from 0.01207
126/126 ━━━━━━━━━━━━━━━━━━━━ 180s 1s/step - loss: 0.0609 - val_loss: 0.0132 - learning_rate: 7.5000e-05
Epoch 75/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 2s/step - loss: 0.0626
Epoch 75: val_loss improved from 0.01207 to 0.01207, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_log.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 258s 2s/step - loss: 0.0620 - val_loss: 0.0121 - learning_rate: 7.5000e-05
Epoch 76/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 2s/step - loss: 0.0634
Epoch 76: val_loss did not improve from 0.01207
126/126 ━━━━━━━━━━━━━━━━━━━━ 219s 2s/step - loss: 0.0620 - val_loss: 0.0131 - learning_rate: 7.5000e-05
Epoch 77/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0609
Epoch 77: val_loss improved from 0.01207 to 0.01195, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_log.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 149s 1s/step - loss: 0.0614 - val_loss: 0.0119 - learning_rate: 7.5000e-05
Epoch 78/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 939ms/step - loss: 0.0629
Epoch 78: val_loss did not improve from 0.01195
126/126 ━━━━━━━━━━━━━━━━━━━━ 124s 990ms/step - loss: 0.0624 - val_loss: 0.0134 - learning_rate: 7.5000e-05
Epoch 79/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 971ms/step - loss: 0.0603
Epoch 79: val_loss did not improve from 0.01195
126/126 ━━━━━━━━━━━━━━━━━━━━ 131s 1s/step - loss: 0.0616 - val_loss: 0.0126 - learning_rate: 7.5000e-05
Epoch 80/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 870ms/step - loss: 0.0612
Epoch 80: val_loss did not improve from 0.01195
126/126 ━━━━━━━━━━━━━━━━━━━━ 117s 932ms/step - loss: 0.0610 - val_loss: 0.0132 - learning_rate: 7.5000e-05
Epoch 81/200

In [33]:
SEQ_LEN = 48
EPOCHS = 200
BATCH = 64
PATIENCE = 20
LSTM_UNITS = 128
LR = 3e-4

results = []

for st_dir in station_dirs:
    st = int(st_dir.name.split("_")[1])

    train_df = pd.read_csv(st_dir / "train.csv")
    val_df   = pd.read_csv(st_dir / "val.csv")
    test_df  = pd.read_csv(st_dir / "test.csv")

    feature_cols = [c for c in train_df.columns if c not in id_cols + [target_col]]

    X_train = train_df[feature_cols].values.astype(np.float32)
    y_train = train_df[target_col].values.astype(np.float32)

    X_val = val_df[feature_cols].values.astype(np.float32)
    y_val = val_df[target_col].values.astype(np.float32)

    X_test = test_df[feature_cols].values.astype(np.float32)
    y_test = test_df[target_col].values.astype(np.float32)

    # ===== y: scaled -> real -> log1p =====
    y_train_real = pm25_scaler.inverse_transform(y_train.reshape(-1,1)).ravel()
    y_val_real   = pm25_scaler.inverse_transform(y_val.reshape(-1,1)).ravel()
    y_test_real  = pm25_scaler.inverse_transform(y_test.reshape(-1,1)).ravel()

    y_train_log = np.log1p(np.clip(y_train_real, 0, None))
    y_val_log   = np.log1p(np.clip(y_val_real, 0, None))
    y_test_log  = np.log1p(np.clip(y_test_real, 0, None))

    ckpt = ARTIFACTS_DIR / f"cnn_bilstm_station{st}_LOG_seq{SEQ_LEN}_u{LSTM_UNITS}.keras"

    # ===== train in log space =====
    model, _ = train_cnn_bilstm(
        X_train, y_train_log,
        X_val, y_val_log,
        seq_len=SEQ_LEN,
        epochs=EPOCHS,
        batch_size=BATCH,
        use_early_stopping=True,
        patience=PATIENCE,
        learning_rate=LR,
        lstm_units=LSTM_UNITS,
        use_attention=True,
        checkpoint_path=str(ckpt)
    )

    best = load_model(ckpt)

    # ===== predict log -> real =====
    y_pred_log = predict_cnn_bilstm(best, X_test, seq_len=SEQ_LEN)
    y_true_log = y_test_log[SEQ_LEN:]

    y_pred_real = np.expm1(y_pred_log)
    y_true_real = np.expm1(y_true_log)

    # clip negative predictions (safety)
    y_pred_real = np.clip(y_pred_real, 0, None)

    # ===== metrics real scale =====
    diff = y_pred_real - y_true_real
    rmse = float(np.sqrt(np.mean(diff**2)))
    mae  = float(np.mean(np.abs(diff)))

    if np.std(y_true_real) < 1e-6 or np.std(y_pred_real) < 1e-6:
        corr = float("nan")
    else:
        corr = float(np.corrcoef(y_pred_real, y_true_real)[0,1])

    mask = np.abs(y_true_real) >= 1.0
    mape = float(np.mean(np.abs(diff[mask]) / np.abs(y_true_real[mask]))) if np.any(mask) else float("nan")

    results.append({
        "Station_No": st,
        "n_test": int(len(y_true_real)),
        "Correlation": corr,
        "RMSE": rmse,
        "MAE": mae,
        "MAPE": mape
    })

    print(f"Station {st} | Corr={corr:.3f} RMSE={rmse:.2f} MAE={mae:.2f} MAPE={mape:.3f}")

results_log_df = pd.DataFrame(results).sort_values("Station_No").reset_index(drop=True)
print("\nMean across stations (LOG-target):")
print(results_log_df[["Correlation","RMSE","MAE","MAPE"]].mean())

results_log_df

Epoch 1/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 651ms/step - loss: 0.5034
Epoch 1: val_loss improved from None to 0.13071, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_LOG_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 114s 717ms/step - loss: 0.2551 - val_loss: 0.1307 - learning_rate: 3.0000e-04
Epoch 2/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 682ms/step - loss: 0.1454
Epoch 2: val_loss improved from 0.13071 to 0.11060, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_LOG_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 92s 734ms/step - loss: 0.1429 - val_loss: 0.1106 - learning_rate: 3.0000e-04
Epoch 3/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 627ms/step - loss: 0.1274
Epoch 3: val_loss did not improve from 0.11060
126/126 ━━━━━━━━━━━━━━━━━━━━ 85s 679ms/step - loss: 0.1260 - val_loss: 0.1434 - learning_rate: 3.0000e-04
Epoch 4/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 638ms/step - loss: 0.1199
Epoch 4: val_loss improved from 0.11060 to 0.10238, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_LOG_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 88s 699ms/step - loss: 0.1193 - val_loss: 0.1024 - learning_rate: 3.0000e-04
Epoch 5/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 654ms/step - loss: 0.1105
Epoch 5: val_loss improved from 0.10238 to 0.08326, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_LOG_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 90s 716ms/step - loss: 0.1100 - val_loss: 0.0833 - learning_rate: 3.0000e-04
Epoch 6/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 608ms/step - loss: 0.1069
Epoch 6: val_loss did not improve from 0.08326
126/126 ━━━━━━━━━━━━━━━━━━━━ 83s 659ms/step - loss: 0.1055 - val_loss: 0.0853 - learning_rate: 3.0000e-04
Epoch 7/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 635ms/step - loss: 0.1033
Epoch 7: val_loss improved from 0.08326 to 0.06677, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_LOG_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 87s 695ms/step - loss: 0.1001 - val_loss: 0.0668 - learning_rate: 3.0000e-04
Epoch 8/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 660ms/step - loss: 0.0997
Epoch 8: val_loss did not improve from 0.06677
126/126 ━━━━━━━━━━━━━━━━━━━━ 90s 712ms/step - loss: 0.0992 - val_loss: 0.0799 - learning_rate: 3.0000e-04
Epoch 9/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 640ms/step - loss: 0.0921
Epoch 9: val_loss improved from 0.06677 to 0.06616, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_LOG_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 88s 696ms/step - loss: 0.0942 - val_loss: 0.0662 - learning_rate: 3.0000e-04
Epoch 10/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 595ms/step - loss: 0.0939
Epoch 10: val_loss improved from 0.06616 to 0.05887, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_LOG_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 82s 654ms/step - loss: 0.0927 - val_loss: 0.0589 - learning_rate: 3.0000e-04
Epoch 11/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 619ms/step - loss: 0.0932
Epoch 11: val_loss did not improve from 0.05887
126/126 ━━━━━━━━━━━━━━━━━━━━ 84s 669ms/step - loss: 0.0907 - val_loss: 0.0641 - learning_rate: 3.0000e-04
Epoch 12/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 614ms/step - loss: 0.0921
Epoch 12: val_loss improved from 0.05887 to 0.05570, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_LOG_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 84s 669ms/step - loss: 0.0895 - val_loss: 0.0557 - learning_rate: 3.0000e-04
Epoch 13/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 621ms/step - loss: 0.0860
Epoch 13: val_loss did not improve from 0.05570
126/126 ━━━━━━━━━━━━━━━━━━━━ 85s 672ms/step - loss: 0.0871 - val_loss: 0.0608 - learning_rate: 3.0000e-04
Epoch 14/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 596ms/step - loss: 0.0879
Epoch 14: val_loss did not improve from 0.05570
126/126 ━━━━━━━━━━━━━━━━━━━━ 81s 647ms/step - loss: 0.0893 - val_loss: 0.0588 - learning_rate: 3.0000e-04
Epoch 15/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 599ms/step - loss: 0.0870
Epoch 15: val_loss improved from 0.05570 to 0.05355, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_LOG_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 82s 652ms/step - loss: 0.0879 - val_loss: 0.0535 - learning_rate: 3.0000e-04
Epoch 16/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 612ms/step - loss: 0.0861
Epoch 16: val_loss improved from 0.05355 to 0.05314, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_LOG_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 84s 664ms/step - loss: 0.0842 - val_loss: 0.0531 - learning_rate: 3.0000e-04
Epoch 17/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 625ms/step - loss: 0.0812
Epoch 17: val_loss did not improve from 0.05314
126/126 ━━━━━━━━━━━━━━━━━━━━ 85s 677ms/step - loss: 0.0825 - val_loss: 0.0542 - learning_rate: 3.0000e-04
Epoch 18/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 665ms/step - loss: 0.0910
Epoch 18: val_loss did not improve from 0.05314
126/126 ━━━━━━━━━━━━━━━━━━━━ 91s 724ms/step - loss: 0.0884 - val_loss: 0.0583 - learning_rate: 3.0000e-04
Epoch 19/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 751ms/step - loss: 0.0882
Epoch 19: val_loss did not improve from 0.05314
126/126 ━━━━━━━━━━━━━━━━━━━━ 102s 808ms/step - loss: 0.0858 - val_loss: 0.0590 - learning_rate: 3.0000e-04
Epoch 20/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 780ms/step - loss: 0.0851
Epoch 20: val_loss improved from 0.05314 to 0.05227, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_LOG_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 106s 840ms/step - loss: 0.0832 - val_loss: 0.0523 - learning_rate: 3.0000e-04
Epoch 21/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 785ms/step - loss: 0.0825
Epoch 21: val_loss improved from 0.05227 to 0.04515, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_LOG_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 107s 853ms/step - loss: 0.0824 - val_loss: 0.0452 - learning_rate: 3.0000e-04
Epoch 22/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 763ms/step - loss: 0.0847
Epoch 22: val_loss did not improve from 0.04515
126/126 ━━━━━━━━━━━━━━━━━━━━ 106s 839ms/step - loss: 0.0851 - val_loss: 0.0536 - learning_rate: 3.0000e-04
Epoch 23/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0836
Epoch 23: val_loss did not improve from 0.04515
126/126 ━━━━━━━━━━━━━━━━━━━━ 145s 1s/step - loss: 0.0799 - val_loss: 0.0575 - learning_rate: 3.0000e-04
Epoch 24/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 750ms/step - loss: 0.0869
Epoch 24: val_loss did not improve from 0.04515
126/126 ━━━━━━━━━━━━━━━━━━━━ 102s 806ms/step - loss: 0.0822 - val_loss: 0.0501 - learning_rate: 3.0000e-04
Epoch 25/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 619ms/step - loss: 0.0814
Epoch 25: val_loss did not improve from 0.04515
126/126 ━━━━━━━━━━━━━━━━━━━━ 84s 666ms/step - loss: 0.0797 - val_loss: 0.0498 - learning_rate: 3.0000e-04
Epoch 26/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 706ms/step - loss: 0.0783
Epoch 26: val_loss did not improve from 0.04515
126/126 ━━━━━━━━━━━━━━━━━━━━ 96s 765ms/step - loss: 0.0819 - val_loss: 0.0600 - learning_rate: 3.0000e-04
Epoch 27/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 699ms/step - loss: 0.0835
Epoch 27: val_loss did not improve from 0.04515
126/126 ━━━━━━━━━━━━━━━━━━━━ 94s 750ms/step - loss: 0.0790 - val_loss: 0.0478 - learning_rate: 3.0000e-04
Epoch 28/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 663ms/step - loss: 0.0754
Epoch 28: val_loss did not improve from 0.04515
126/126 ━━━━━━━━━━━━━━━━━━━━ 90s 718ms/step - loss: 0.0777 - val_loss: 0.0603 - learning_rate: 3.0000e-04
Epoch 29/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 638ms/step - loss: 0.0794
Epoch 29: val_loss did not improve from 0.04515
126/126 ━━━━━━━━━━━━━━━━━━━━ 87s 690ms/step - loss: 0.0797 - val_loss: 0.0510 - learning_rate: 3.0000e-04
Epoch 30/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 676ms/step - loss: 0.0749
Epoch 30: val_loss did not improve from 0.04515
126/126 ━━━━━━━━━━━━━━━━━━━━ 92s 735ms/step - loss: 0.0752 - val_loss: 0.0522 - learning_rate: 3.0000e-04
Epoch 31/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 661ms/step - loss: 0.0758
Epoch 31: val_loss did not improve from 0.04515

Epoch 31: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.
126/126 ━━━━━━━━━━━━━━━━━━━━ 90s 711ms/step - loss: 0.0762 - val_loss: 0.0492 - learning_rate: 3.0000e-04
Epoch 32/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 640ms/step - loss: 0.0764
Epoch 32: val_loss improved from 0.04515 to 0.04187, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_LOG_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 88s 697ms/step - loss: 0.0753 - val_loss: 0.0419 - learning_rate: 1.5000e-04
Epoch 33/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 713ms/step - loss: 0.0751
Epoch 33: val_loss did not improve from 0.04187
126/126 ━━━━━━━━━━━━━━━━━━━━ 96s 764ms/step - loss: 0.0753 - val_loss: 0.0419 - learning_rate: 1.5000e-04
Epoch 34/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 630ms/step - loss: 0.0734
Epoch 34: val_loss did not improve from 0.04187
126/126 ━━━━━━━━━━━━━━━━━━━━ 86s 681ms/step - loss: 0.0735 - val_loss: 0.0458 - learning_rate: 1.5000e-04
Epoch 35/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 634ms/step - loss: 0.0711
Epoch 35: val_loss did not improve from 0.04187
126/126 ━━━━━━━━━━━━━━━━━━━━ 87s 689ms/step - loss: 0.0736 - val_loss: 0.0430 - learning_rate: 1.5000e-04
Epoch 36/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 653ms/step - loss: 0.0745
Epoch 36: val_loss did not improve from 0.04187
126/126 ━━━━━━━━━━━━━━━━━━━━ 89s 703ms/step - loss: 0.0755 - val_loss: 0.0419 - learning_rate: 1.5000e-04
Epoch 37/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 631ms/step - loss: 0.0736
Epoch 37: val_loss did not improve from 0.04187
126/126 ━━━━━━━━━━━━━━━━━━━━ 86s 683ms/step - loss: 0.0742 - val_loss: 0.0474 - learning_rate: 1.5000e-04
Epoch 38/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 633ms/step - loss: 0.0764
Epoch 38: val_loss did not improve from 0.04187
126/126 ━━━━━━━━━━━━━━━━━━━━ 94s 750ms/step - loss: 0.0719 - val_loss: 0.0453 - learning_rate: 1.5000e-04
Epoch 39/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 646ms/step - loss: 0.0726
Epoch 39: val_loss did not improve from 0.04187
126/126 ━━━━━━━━━━━━━━━━━━━━ 90s 708ms/step - loss: 0.0742 - val_loss: 0.0423 - learning_rate: 1.5000e-04
Epoch 40/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 650ms/step - loss: 0.0736
Epoch 40: val_loss did not improve from 0.04187
126/126 ━━━━━━━━━━━━━━━━━━━━ 89s 710ms/step - loss: 0.0727 - val_loss: 0.0434 - learning_rate: 1.5000e-04
Epoch 41/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 617ms/step - loss: 0.0733
Epoch 41: val_loss did not improve from 0.04187
126/126 ━━━━━━━━━━━━━━━━━━━━ 84s 667ms/step - loss: 0.0745 - val_loss: 0.0457 - learning_rate: 1.5000e-04
Epoch 42/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 605ms/step - loss: 0.0724
Epoch 42: val_loss improved from 0.04187 to 0.04125, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_LOG_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 83s 657ms/step - loss: 0.0725 - val_loss: 0.0412 - learning_rate: 1.5000e-04
Epoch 43/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 650ms/step - loss: 0.0733
Epoch 43: val_loss improved from 0.04125 to 0.04022, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_LOG_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 89s 711ms/step - loss: 0.0726 - val_loss: 0.0402 - learning_rate: 1.5000e-04
Epoch 44/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 514ms/step - loss: 0.0739
Epoch 44: val_loss improved from 0.04022 to 0.04021, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_LOG_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 126s 579ms/step - loss: 0.0712 - val_loss: 0.0402 - learning_rate: 1.5000e-04
Epoch 45/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 628ms/step - loss: 0.0689
Epoch 45: val_loss did not improve from 0.04021
126/126 ━━━━━━━━━━━━━━━━━━━━ 85s 679ms/step - loss: 0.0709 - val_loss: 0.0405 - learning_rate: 1.5000e-04
Epoch 46/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 632ms/step - loss: 0.0755
Epoch 46: val_loss did not improve from 0.04021
126/126 ━━━━━━━━━━━━━━━━━━━━ 87s 689ms/step - loss: 0.0731 - val_loss: 0.0403 - learning_rate: 1.5000e-04
Epoch 47/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 693ms/step - loss: 0.0722
Epoch 47: val_loss did not improve from 0.04021
126/126 ━━━━━━━━━━━━━━━━━━━━ 93s 742ms/step - loss: 0.0714 - val_loss: 0.0427 - learning_rate: 1.5000e-04
Epoch 48/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 629ms/step - loss: 0.0744
Epoch 48: val_loss did not improve from 0.04021
126/126 ━━━━━━━━━━━━━━━━━━━━ 86s 683ms/step - loss: 0.0706 - val_loss: 0.0411 - learning_rate: 1.5000e-04
Epoch 49/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 673ms/step - loss: 0.0710
Epoch 49: val_loss did not improve from 0.04021
126/126 ━━━━━━━━━━━━━━━━━━━━ 91s 725ms/step - loss: 0.0705 - val_loss: 0.0403 - learning_rate: 1.5000e-04
Epoch 50/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 653ms/step - loss: 0.0695
Epoch 50: val_loss did not improve from 0.04021
126/126 ━━━━━━━━━━━━━━━━━━━━ 89s 710ms/step - loss: 0.0706 - val_loss: 0.0412 - learning_rate: 1.5000e-04
Epoch 51/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 655ms/step - loss: 0.0733
Epoch 51: val_loss did not improve from 0.04021
126/126 ━━━━━━━━━━━━━━━━━━━━ 90s 714ms/step - loss: 0.0718 - val_loss: 0.0404 - learning_rate: 1.5000e-04
Epoch 52/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 608ms/step - loss: 0.0683
Epoch 52: val_loss improved from 0.04021 to 0.03884, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_LOG_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 83s 661ms/step - loss: 0.0689 - val_loss: 0.0388 - learning_rate: 1.5000e-04
Epoch 53/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 624ms/step - loss: 0.0683
Epoch 53: val_loss did not improve from 0.03884
126/126 ━━━━━━━━━━━━━━━━━━━━ 85s 673ms/step - loss: 0.0690 - val_loss: 0.0446 - learning_rate: 1.5000e-04
Epoch 54/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 644ms/step - loss: 0.0728
Epoch 54: val_loss did not improve from 0.03884
126/126 ━━━━━━━━━━━━━━━━━━━━ 88s 700ms/step - loss: 0.0711 - val_loss: 0.0485 - learning_rate: 1.5000e-04
Epoch 55/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 608ms/step - loss: 0.0692
Epoch 55: val_loss did not improve from 0.03884
126/126 ━━━━━━━━━━━━━━━━━━━━ 83s 659ms/step - loss: 0.0685 - val_loss: 0.0396 - learning_rate: 1.5000e-04
Epoch 56/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 604ms/step - loss: 0.0730
Epoch 56: val_loss did not improve from 0.03884
126/126 ━━━━━━━━━━━━━━━━━━━━ 83s 658ms/step - loss: 0.0706 - val_loss: 0.0422 - learning_rate: 1.5000e-04
Epoch 57/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 621ms/step - loss: 0.0675
Epoch 57: val_loss did not improve from 0.03884
126/126 ━━━━━━━━━━━━━━━━━━━━ 86s 682ms/step - loss: 0.0686 - val_loss: 0.0445 - learning_rate: 1.5000e-04
Epoch 58/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 600ms/step - loss: 0.0686
Epoch 58: val_loss did not improve from 0.03884
126/126 ━━━━━━━━━━━━━━━━━━━━ 82s 648ms/step - loss: 0.0703 - val_loss: 0.0434 - learning_rate: 1.5000e-04
Epoch 59/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 604ms/step - loss: 0.0694
Epoch 59: val_loss did not improve from 0.03884
126/126 ━━━━━━━━━━━━━━━━━━━━ 82s 652ms/step - loss: 0.0707 - val_loss: 0.0424 - learning_rate: 1.5000e-04
Epoch 60/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 603ms/step - loss: 0.0691
Epoch 60: val_loss did not improve from 0.03884
126/126 ━━━━━━━━━━━━━━━━━━━━ 83s 660ms/step - loss: 0.0696 - val_loss: 0.0394 - learning_rate: 1.5000e-04
Epoch 61/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 588ms/step - loss: 0.0665
Epoch 61: val_loss did not improve from 0.03884
126/126 ━━━━━━━━━━━━━━━━━━━━ 80s 639ms/step - loss: 0.0673 - val_loss: 0.0437 - learning_rate: 1.5000e-04
Epoch 62/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 584ms/step - loss: 0.0660
Epoch 62: val_loss improved from 0.03884 to 0.03875, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_LOG_seq48_u128.keras

Epoch 62: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
126/126 ━━━━━━━━━━━━━━━━━━━━ 80s 637ms/step - loss: 0.0673 - val_loss: 0.0387 - learning_rate: 1.5000e-04
Epoch 63/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 589ms/step - loss: 0.0665
Epoch 63: val_loss did not improve from 0.03875
126/126 ━━━━━━━━━━━━━━━━━━━━ 80s 635ms/step - loss: 0.0661 - val_loss: 0.0406 - learning_rate: 7.5000e-05
Epoch 64/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 605ms/step - loss: 0.0653
Epoch 64: val_loss improved from 0.03875 to 0.03842, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_LOG_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 83s 656ms/step - loss: 0.0658 - val_loss: 0.0384 - learning_rate: 7.5000e-05
Epoch 65/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 602ms/step - loss: 0.0660
Epoch 65: val_loss did not improve from 0.03842
126/126 ━━━━━━━━━━━━━━━━━━━━ 83s 663ms/step - loss: 0.0651 - val_loss: 0.0405 - learning_rate: 7.5000e-05
Epoch 66/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 577ms/step - loss: 0.0672
Epoch 66: val_loss did not improve from 0.03842
126/126 ━━━━━━━━━━━━━━━━━━━━ 78s 621ms/step - loss: 0.0671 - val_loss: 0.0390 - learning_rate: 7.5000e-05
Epoch 67/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 572ms/step - loss: 0.0671
Epoch 67: val_loss did not improve from 0.03842
126/126 ━━━━━━━━━━━━━━━━━━━━ 79s 627ms/step - loss: 0.0681 - val_loss: 0.0409 - learning_rate: 7.5000e-05
Epoch 68/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 579ms/step - loss: 0.0672
Epoch 68: val_loss did not improve from 0.03842
126/126 ━━━━━━━━━━━━━━━━━━━━ 79s 627ms/step - loss: 0.0657 - val_loss: 0.0421 - learning_rate: 7.5000e-05
Epoch 69/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 607ms/step - loss: 0.0691
Epoch 69: val_loss did not improve from 0.03842
126/126 ━━━━━━━━━━━━━━━━━━━━ 83s 660ms/step - loss: 0.0693 - val_loss: 0.0407 - learning_rate: 7.5000e-05
Epoch 70/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 592ms/step - loss: 0.0672
Epoch 70: val_loss did not improve from 0.03842
126/126 ━━━━━━━━━━━━━━━━━━━━ 81s 640ms/step - loss: 0.0660 - val_loss: 0.0433 - learning_rate: 7.5000e-05
Epoch 71/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 583ms/step - loss: 0.0669
Epoch 71: val_loss did not improve from 0.03842
126/126 ━━━━━━━━━━━━━━━━━━━━ 79s 630ms/step - loss: 0.0673 - val_loss: 0.0393 - learning_rate: 7.5000e-05
Epoch 72/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 598ms/step - loss: 0.0641
Epoch 72: val_loss improved from 0.03842 to 0.03771, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_LOG_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 81s 646ms/step - loss: 0.0658 - val_loss: 0.0377 - learning_rate: 7.5000e-05
Epoch 73/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 591ms/step - loss: 0.0673
Epoch 73: val_loss did not improve from 0.03771
126/126 ━━━━━━━━━━━━━━━━━━━━ 81s 645ms/step - loss: 0.0673 - val_loss: 0.0388 - learning_rate: 7.5000e-05
Epoch 74/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 586ms/step - loss: 0.0657
Epoch 74: val_loss did not improve from 0.03771
126/126 ━━━━━━━━━━━━━━━━━━━━ 80s 637ms/step - loss: 0.0664 - val_loss: 0.0387 - learning_rate: 7.5000e-05
Epoch 75/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 588ms/step - loss: 0.0676
Epoch 75: val_loss did not improve from 0.03771
126/126 ━━━━━━━━━━━━━━━━━━━━ 80s 638ms/step - loss: 0.0668 - val_loss: 0.0403 - learning_rate: 7.5000e-05
Epoch 76/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 571ms/step - loss: 0.0661
Epoch 76: val_loss did not improve from 0.03771
126/126 ━━━━━━━━━━━━━━━━━━━━ 79s 626ms/step - loss: 0.0651 - val_loss: 0.0387 - learning_rate: 7.5000e-05
Epoch 77/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 580ms/step - loss: 0.0670
Epoch 77: val_loss did not improve from 0.03771
126/126 ━━━━━━━━━━━━━━━━━━━━ 79s 628ms/step - loss: 0.0657 - val_loss: 0.0398 - learning_rate: 7.5000e-05
Epoch 78/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 591ms/step - loss: 0.0679
Epoch 78: val_loss did not improve from 0.03771

   Station_No  n_test  Correlation       RMSE        MAE      MAPE
0           1    1691     0.850262  45.962128  31.457357  0.318530
1           2    1691     0.866036  24.249121  15.471744  0.124699
2           3    1691     0.874539  32.602165  21.116827  0.246614
3           4    1691     0.880597  40.039757  26.946671  0.145984
4           5    1691     0.945971  20.337324  14.977503  0.132320
5           6    1689     0.900549  24.954287  16.541933  0.124064

In [34]:
print(train_df.shape, val_df.shape, test_df.shape)
print(train_df["date"].min(), train_df["date"].max())

(8098, 35) (1735, 35) (1737, 35)
2021-02-24 16:00:00 2022-01-28 01:00:00