In [1]:
from _setup import setup_project_root
PROJECT_ROOT = setup_project_root()
PROJECT_ROOT

WindowsPath('C:/AirPollutionPrediction-CNN-BiLSTM')

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path
import joblib
import tensorflow as tf
load_model = tf.keras.models.load_model

from models.cnn_bilstm import train_cnn_bilstm, predict_cnn_bilstm

In [3]:
PROJECT_ROOT = Path.cwd().parent   
DATA_DIR = PROJECT_ROOT / "data"
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"

STATION_SPLIT_DIR = DATA_DIR / "station_split_24havg"   
pm25_scaler = joblib.load(ARTIFACTS_DIR / "pm25_scaler.pkl")

print("PROJECT_ROOT:", PROJECT_ROOT)
print("STATION_SPLIT_DIR exists:", STATION_SPLIT_DIR.exists())
print("Loaded pm25_scaler:", ARTIFACTS_DIR / "pm25_scaler.pkl")

PROJECT_ROOT: c:\AirPollutionPrediction-CNN-BiLSTM
STATION_SPLIT_DIR exists: True
Loaded pm25_scaler: c:\AirPollutionPrediction-CNN-BiLSTM\artifacts\pm25_scaler.pkl

c:\Users\KimNgan\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:463: InconsistentVersionWarning: Trying to unpickle estimator MinMaxScaler from version 1.5.1 when using version 1.8.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [4]:
target_col = "PM2.5_24h_avg"
id_cols = ["Station_No", "date"]

SEQ_LEN = 48
EPOCHS = 200
BATCH = 64
PATIENCE = 20
LR = 3e-4
LSTM_UNITS = 128

print("Target:", target_col)
print("SEQ_LEN:", SEQ_LEN)

Target: PM2.5_24h_avg
SEQ_LEN: 48

In [5]:
import numpy as np
from sklearn.metrics import r2_score

def metrics_real_from_scaled(y_true_scaled, y_pred_scaled, scaler, eps=1e-6, mape_threshold=1.0):
    # Đảm bảo đầu vào là mảng phẳng
    y_true_scaled = np.asarray(y_true_scaled).reshape(-1)
    y_pred_scaled = np.asarray(y_pred_scaled).reshape(-1)

    # Giải mã (Inverse Transform) về đơn vị thực tế (µg/m³)
    yt = scaler.inverse_transform(y_true_scaled.reshape(-1,1)).ravel()
    yp = scaler.inverse_transform(y_pred_scaled.reshape(-1,1)).ravel()

    # Tính toán các chỉ số cơ bản
    diff = yp - yt
    mae = float(np.mean(np.abs(diff)))
    rmse = float(np.sqrt(np.mean(diff**2)))

    # --- TÍNH R^2 SCORE ---
    # R2 = 1 là dự báo hoàn hảo. R2 = 0 là dự báo bằng giá trị trung bình.
    r2 = float(r2_score(yt, yp))

    # Tính MAPE với ngưỡng loại bỏ giá trị nhỏ (tránh chia cho ~0)
    mask = np.abs(yt) >= mape_threshold
    mape = float(np.mean(np.abs(diff[mask]) / np.abs(yt[mask]))) if np.any(mask) else float("nan")

    # Tính Hệ số tương quan Pearson (Correlation)
    if np.std(yt) < eps or np.std(yp) < eps:
        corr = float("nan")
    else:
        corr = float(np.corrcoef(yt, yp)[0,1])

    return {
        "Correlation": corr, 
        "R2": r2,           # Chỉ số mới
        "RMSE": rmse, 
        "MAPE": mape, 
        "MAE": mae
    }

In [6]:
station_dirs = sorted([p for p in STATION_SPLIT_DIR.glob("station_*") if p.is_dir()],
                      key=lambda p: int(p.name.split("_")[1]))

print("Found stations:", [p.name for p in station_dirs])

Found stations: ['station_1', 'station_2', 'station_3', 'station_4', 'station_5', 'station_6']

In [7]:
st_dir = STATION_SPLIT_DIR / "station_1"

train_df = pd.read_csv(st_dir / "train.csv")
val_df   = pd.read_csv(st_dir / "val.csv")
test_df  = pd.read_csv(st_dir / "test.csv")

feature_cols = [c for c in train_df.columns if c not in (id_cols + [target_col])]

X_train = train_df[feature_cols].values.astype(np.float32)
y_train = train_df[target_col].values.astype(np.float32)

X_val = val_df[feature_cols].values.astype(np.float32)
y_val = val_df[target_col].values.astype(np.float32)

X_test = test_df[feature_cols].values.astype(np.float32)
y_test = test_df[target_col].values.astype(np.float32)

print("Shapes:", X_train.shape, X_val.shape, X_test.shape)
print("Num features:", len(feature_cols))

Shapes: (8096, 33) (1734, 33) (1736, 33)
Num features: 33

In [ ]:
ckpt = ARTIFACTS_DIR / f"cnn_bilstm_station1_24havg_seq{SEQ_LEN}_u{LSTM_UNITS}.keras"

model, history = train_cnn_bilstm(
    X_train, y_train,
    X_val, y_val,
    seq_len=SEQ_LEN,
    epochs=EPOCHS,
    batch_size=BATCH,
    use_early_stopping=True,
    patience=PATIENCE,
    learning_rate=LR,
    lstm_units=LSTM_UNITS,
    use_attention=True,
    checkpoint_path=str(ckpt)
)

best = load_model(ckpt)

y_pred_scaled = predict_cnn_bilstm(best, X_test, seq_len=SEQ_LEN)
y_true_scaled = y_test[SEQ_LEN:]

m1 = metrics_real_from_scaled(y_true_scaled, y_pred_scaled, pm25_scaler, eps=1.0)

print("\nStation 1 - 24hAVG (REAL SCALE µg/m³):")
for k,v in m1.items():
    print(f"{k}: {v}")

Epoch 1/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 0.0957
Epoch 1: val_loss improved from None to 0.00265, saving model to c:\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras

Epoch 1: finished saving model to c:\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 21s 112ms/step - loss: 0.0353 - val_loss: 0.0027 - learning_rate: 3.0000e-04
Epoch 2/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - loss: 0.0052
Epoch 2: val_loss improved from 0.00265 to 0.00213, saving model to c:\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras

Epoch 2: finished saving model to c:\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 15s 120ms/step - loss: 0.0048 - val_loss: 0.0021 - learning_rate: 3.0000e-04
Epoch 3/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - loss: 0.0041
Epoch 3: val_loss improved from 0.00213 to 0.00142, saving model to c:\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras

Epoch 3: finished saving model to c:\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 16s 124ms/step - loss: 0.0038 - val_loss: 0.0014 - learning_rate: 3.0000e-04
Epoch 4/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - loss: 0.0030
Epoch 4: val_loss improved from 0.00142 to 0.00094, saving model to c:\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras

Epoch 4: finished saving model to c:\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 17s 136ms/step - loss: 0.0029 - val_loss: 9.4499e-04 - learning_rate: 3.0000e-04
Epoch 5/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - loss: 0.0026
Epoch 5: val_loss improved from 0.00094 to 0.00087, saving model to c:\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras

Epoch 5: finished saving model to c:\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 18s 145ms/step - loss: 0.0025 - val_loss: 8.6814e-04 - learning_rate: 3.0000e-04
Epoch 6/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 247ms/step - loss: 0.0023
Epoch 6: val_loss improved from 0.00087 to 0.00079, saving model to c:\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras

Epoch 6: finished saving model to c:\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 34s 268ms/step - loss: 0.0022 - val_loss: 7.9352e-04 - learning_rate: 3.0000e-04
Epoch 7/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 213ms/step - loss: 0.0019
Epoch 7: val_loss improved from 0.00079 to 0.00060, saving model to c:\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras

Epoch 7: finished saving model to c:\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 37s 238ms/step - loss: 0.0019 - val_loss: 5.9860e-04 - learning_rate: 3.0000e-04
Epoch 8/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 219ms/step - loss: 0.0018
Epoch 8: val_loss improved from 0.00060 to 0.00047, saving model to c:\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras

Epoch 8: finished saving model to c:\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 41s 237ms/step - loss: 0.0017 - val_loss: 4.6974e-04 - learning_rate: 3.0000e-04
Epoch 9/200
 81/126 ━━━━━━━━━━━━━━━━━━━━ 5s 128ms/step - loss: 0.0018

In [10]:
import keras
import pandas as pd
from sklearn.metrics import r2_score

# Danh sách để lưu kết quả của từng trạm
summary_list = []

for i in range(1, 7): # Chạy từ 1 đến 6
    ckpt = rf'C:\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station{i}_24havg_seq48_u128.keras'
    print(f"Đang xử lý: Station {i}...", end="\r")
    
    try:
        # 1. Load model
        model = keras.models.load_model(ckpt)

        # 2. Dự đoán
        y_pred_scaled = predict_cnn_bilstm(model, X_test, seq_len=SEQ_LEN)
        y_true_scaled = y_test[SEQ_LEN:]

        # 3. Tính toán Metrics (hàm của bạn)
        m = metrics_real_from_scaled(y_true_scaled, y_pred_scaled, pm25_scaler, eps=1.0)
        
        # 4. Thêm tên trạm vào kết quả
        m['Station'] = f"Station {i}"
        
        # Thêm R2_Score nếu chưa có
        if 'R2_Score' not in m:
            m['R2_Score'] = r2_score(y_true_scaled, y_pred_scaled)

        # 5. Lưu vào danh sách tổng
        summary_list.append(m)
        
        # Xóa model để nhẹ máy
        keras.backend.clear_session()
        
    except Exception as e:
        print(f"\nLỗi tại Station {i}: {e}")

# --- XUẤT KẾT QUẢ ---
# Chuyển danh sách thành DataFrame
df_results = pd.DataFrame(summary_list)

# Đưa cột 'Station' lên đầu bảng
cols = ['Station'] + [c for c in df_results.columns if c != 'Station']
df_results = df_results[cols]

print("\n" + "="*50)
print("BẢNG TỔNG HỢP KẾT QUẢ 6 TRẠM")
print("="*50)
print(df_results.to_string(index=False)) # to_string giúp hiển thị toàn bộ không bị cắt

# Tùy chọn: Lưu ra file Excel để nộp báo cáo
# df_results.to_excel("Ket_qua_6_station.xlsx", index=False)

Đang xử lý: Station 6...
==================================================
BẢNG TỔNG HỢP KẾT QUẢ 6 TRẠM
==================================================
  Station  Correlation       R2      RMSE     MAPE       MAE  R2_Score
Station 1     0.985773 0.968292 10.531547 0.102112  7.101685  0.968292
Station 2     0.985282 0.956566 12.326155 0.129841  8.234040  0.956566
Station 3     0.980081 0.923389 16.370243 0.152265 14.574527  0.923389
Station 4     0.881140 0.512455 41.296982 0.380498 38.055485  0.512455
Station 5     0.976746 0.938069 14.718525 0.130358 10.868428  0.938069
Station 6     0.972603 0.907946 17.944580 0.196480 14.325096  0.907946

In [12]:
all_rows = []

for st_dir in station_dirs:
    st = int(st_dir.name.split("_")[1])

    train_df = pd.read_csv(st_dir / "train.csv")
    val_df   = pd.read_csv(st_dir / "val.csv")
    test_df  = pd.read_csv(st_dir / "test.csv")

    X_train = train_df[feature_cols].values.astype(np.float32)
    y_train = train_df[target_col].values.astype(np.float32)

    X_val = val_df[feature_cols].values.astype(np.float32)
    y_val = val_df[target_col].values.astype(np.float32)

    X_test = test_df[feature_cols].values.astype(np.float32)
    y_test = test_df[target_col].values.astype(np.float32)

    ckpt = ARTIFACTS_DIR / f"cnn_bilstm_station{st}_24havg_seq{SEQ_LEN}_u{LSTM_UNITS}.keras"

    model, _ = train_cnn_bilstm(
        X_train, y_train,
        X_val, y_val,
        seq_len=SEQ_LEN,
        epochs=EPOCHS,
        batch_size=BATCH,
        use_early_stopping=True,
        patience=PATIENCE,
        learning_rate=LR,
        lstm_units=LSTM_UNITS,
        use_attention=True,
        checkpoint_path=str(ckpt)
    )

    best = load_model(ckpt)

    y_pred_scaled = predict_cnn_bilstm(best, X_test, seq_len=SEQ_LEN)
    y_true_scaled = y_test[SEQ_LEN:]

    m = metrics_real_from_scaled(y_true_scaled, y_pred_scaled, pm25_scaler, eps=1.0)
    row = {"Station_No": st, "n_test": int(len(y_true_scaled))}
    row.update(m)
    all_rows.append(row)

    print(f"Station {st} | Corr={m['Correlation']:.3f} RMSE={m['RMSE']:.2f} MAE={m['MAE']:.2f} MAPE={m['MAPE']:.3f}")

results_df = pd.DataFrame(all_rows).sort_values("Station_No").reset_index(drop=True)
results_df

Epoch 1/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 315ms/step - loss: 0.1095
Epoch 1: val_loss improved from None to 0.00317, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 67s 357ms/step - loss: 0.0381 - val_loss: 0.0032 - learning_rate: 3.0000e-04
Epoch 2/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 513ms/step - loss: 0.0051
Epoch 2: val_loss improved from 0.00317 to 0.00304, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 109s 573ms/step - loss: 0.0048 - val_loss: 0.0030 - learning_rate: 3.0000e-04
Epoch 3/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0041
Epoch 3: val_loss improved from 0.00304 to 0.00204, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 162s 1s/step - loss: 0.0038 - val_loss: 0.0020 - learning_rate: 3.0000e-04
Epoch 4/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0034
Epoch 4: val_loss improved from 0.00204 to 0.00162, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 159s 1s/step - loss: 0.0032 - val_loss: 0.0016 - learning_rate: 3.0000e-04
Epoch 5/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 801ms/step - loss: 0.0029
Epoch 5: val_loss improved from 0.00162 to 0.00120, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 105s 836ms/step - loss: 0.0028 - val_loss: 0.0012 - learning_rate: 3.0000e-04
Epoch 6/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 441ms/step - loss: 0.0024
Epoch 6: val_loss improved from 0.00120 to 0.00091, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 60s 479ms/step - loss: 0.0023 - val_loss: 9.0726e-04 - learning_rate: 3.0000e-04
Epoch 7/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 422ms/step - loss: 0.0022
Epoch 7: val_loss improved from 0.00091 to 0.00077, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 57s 455ms/step - loss: 0.0022 - val_loss: 7.7473e-04 - learning_rate: 3.0000e-04
Epoch 8/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 448ms/step - loss: 0.0022
Epoch 8: val_loss improved from 0.00077 to 0.00065, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 61s 481ms/step - loss: 0.0021 - val_loss: 6.4612e-04 - learning_rate: 3.0000e-04
Epoch 9/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 440ms/step - loss: 0.0018
Epoch 9: val_loss improved from 0.00065 to 0.00057, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 59s 473ms/step - loss: 0.0018 - val_loss: 5.7360e-04 - learning_rate: 3.0000e-04
Epoch 10/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 425ms/step - loss: 0.0017
Epoch 10: val_loss improved from 0.00057 to 0.00049, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 58s 460ms/step - loss: 0.0017 - val_loss: 4.8694e-04 - learning_rate: 3.0000e-04
Epoch 11/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 403ms/step - loss: 0.0016
Epoch 11: val_loss improved from 0.00049 to 0.00043, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 55s 435ms/step - loss: 0.0016 - val_loss: 4.3197e-04 - learning_rate: 3.0000e-04
Epoch 12/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 439ms/step - loss: 0.0015
Epoch 12: val_loss improved from 0.00043 to 0.00034, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 60s 473ms/step - loss: 0.0015 - val_loss: 3.4407e-04 - learning_rate: 3.0000e-04
Epoch 13/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 412ms/step - loss: 0.0015
Epoch 13: val_loss did not improve from 0.00034
126/126 ━━━━━━━━━━━━━━━━━━━━ 56s 448ms/step - loss: 0.0015 - val_loss: 6.2171e-04 - learning_rate: 3.0000e-04
Epoch 14/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 450ms/step - loss: 0.0015
Epoch 14: val_loss improved from 0.00034 to 0.00031, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 61s 486ms/step - loss: 0.0015 - val_loss: 3.0527e-04 - learning_rate: 3.0000e-04
Epoch 15/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 462ms/step - loss: 0.0014
Epoch 15: val_loss improved from 0.00031 to 0.00029, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 63s 497ms/step - loss: 0.0013 - val_loss: 2.9266e-04 - learning_rate: 3.0000e-04
Epoch 16/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 436ms/step - loss: 0.0014
Epoch 16: val_loss did not improve from 0.00029
126/126 ━━━━━━━━━━━━━━━━━━━━ 59s 467ms/step - loss: 0.0014 - val_loss: 3.6016e-04 - learning_rate: 3.0000e-04
Epoch 17/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 447ms/step - loss: 0.0012
Epoch 17: val_loss did not improve from 0.00029
126/126 ━━━━━━━━━━━━━━━━━━━━ 61s 481ms/step - loss: 0.0012 - val_loss: 3.7208e-04 - learning_rate: 3.0000e-04
Epoch 18/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 426ms/step - loss: 0.0011
Epoch 18: val_loss improved from 0.00029 to 0.00025, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 59s 465ms/step - loss: 0.0012 - val_loss: 2.4792e-04 - learning_rate: 3.0000e-04
Epoch 19/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 461ms/step - loss: 0.0012
Epoch 19: val_loss did not improve from 0.00025
126/126 ━━━━━━━━━━━━━━━━━━━━ 62s 493ms/step - loss: 0.0011 - val_loss: 3.9520e-04 - learning_rate: 3.0000e-04
Epoch 20/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 461ms/step - loss: 0.0011
Epoch 20: val_loss did not improve from 0.00025
126/126 ━━━━━━━━━━━━━━━━━━━━ 62s 492ms/step - loss: 0.0010 - val_loss: 3.9464e-04 - learning_rate: 3.0000e-04
Epoch 21/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 443ms/step - loss: 9.9817e-04
Epoch 21: val_loss improved from 0.00025 to 0.00023, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 60s 477ms/step - loss: 9.9586e-04 - val_loss: 2.3073e-04 - learning_rate: 3.0000e-04
Epoch 22/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 420ms/step - loss: 0.0010
Epoch 22: val_loss did not improve from 0.00023
126/126 ━━━━━━━━━━━━━━━━━━━━ 57s 452ms/step - loss: 0.0010 - val_loss: 3.0558e-04 - learning_rate: 3.0000e-04
Epoch 23/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 437ms/step - loss: 9.6462e-04
Epoch 23: val_loss did not improve from 0.00023
126/126 ━━━━━━━━━━━━━━━━━━━━ 60s 479ms/step - loss: 9.4269e-04 - val_loss: 2.6233e-04 - learning_rate: 3.0000e-04
Epoch 24/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 422ms/step - loss: 8.9857e-04
Epoch 24: val_loss did not improve from 0.00023
126/126 ━━━━━━━━━━━━━━━━━━━━ 57s 454ms/step - loss: 9.1632e-04 - val_loss: 3.2408e-04 - learning_rate: 3.0000e-04
Epoch 25/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 431ms/step - loss: 9.2663e-04
Epoch 25: val_loss did not improve from 0.00023
126/126 ━━━━━━━━━━━━━━━━━━━━ 58s 465ms/step - loss: 9.2346e-04 - val_loss: 2.3987e-04 - learning_rate: 3.0000e-04
Epoch 26/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 435ms/step - loss: 8.9272e-04
Epoch 26: val_loss did not improve from 0.00023
126/126 ━━━━━━━━━━━━━━━━━━━━ 59s 466ms/step - loss: 9.0379e-04 - val_loss: 3.2498e-04 - learning_rate: 3.0000e-04
Epoch 27/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 497ms/step - loss: 8.4208e-04
Epoch 27: val_loss improved from 0.00023 to 0.00019, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 68s 539ms/step - loss: 8.1026e-04 - val_loss: 1.9434e-04 - learning_rate: 3.0000e-04
Epoch 28/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 430ms/step - loss: 8.1682e-04
Epoch 28: val_loss did not improve from 0.00019
126/126 ━━━━━━━━━━━━━━━━━━━━ 58s 463ms/step - loss: 8.0227e-04 - val_loss: 2.2104e-04 - learning_rate: 3.0000e-04
Epoch 29/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 425ms/step - loss: 7.8824e-04
Epoch 29: val_loss improved from 0.00019 to 0.00019, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 58s 461ms/step - loss: 7.7643e-04 - val_loss: 1.9368e-04 - learning_rate: 3.0000e-04
Epoch 30/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 442ms/step - loss: 7.0771e-04
Epoch 30: val_loss did not improve from 0.00019
126/126 ━━━━━━━━━━━━━━━━━━━━ 60s 475ms/step - loss: 6.9548e-04 - val_loss: 2.7961e-04 - learning_rate: 3.0000e-04
Epoch 31/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 428ms/step - loss: 7.4628e-04
Epoch 31: val_loss did not improve from 0.00019

Epoch 31: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.
126/126 ━━━━━━━━━━━━━━━━━━━━ 58s 459ms/step - loss: 7.2959e-04 - val_loss: 3.0420e-04 - learning_rate: 3.0000e-04
Epoch 32/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 424ms/step - loss: 6.4639e-04
Epoch 32: val_loss did not improve from 0.00019
126/126 ━━━━━━━━━━━━━━━━━━━━ 58s 457ms/step - loss: 6.4494e-04 - val_loss: 2.1783e-04 - learning_rate: 1.5000e-04
Epoch 33/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 428ms/step - loss: 6.4835e-04
Epoch 33: val_loss improved from 0.00019 to 0.00016, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 58s 462ms/step - loss: 6.4079e-04 - val_loss: 1.6489e-04 - learning_rate: 1.5000e-04
Epoch 34/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 427ms/step - loss: 6.2500e-04
Epoch 34: val_loss did not improve from 0.00016
126/126 ━━━━━━━━━━━━━━━━━━━━ 58s 459ms/step - loss: 6.3662e-04 - val_loss: 1.6842e-04 - learning_rate: 1.5000e-04
Epoch 35/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 464ms/step - loss: 6.1094e-04
Epoch 35: val_loss did not improve from 0.00016
126/126 ━━━━━━━━━━━━━━━━━━━━ 62s 496ms/step - loss: 6.0058e-04 - val_loss: 1.7690e-04 - learning_rate: 1.5000e-04
Epoch 36/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 429ms/step - loss: 6.0252e-04
Epoch 36: val_loss did not improve from 0.00016
126/126 ━━━━━━━━━━━━━━━━━━━━ 58s 462ms/step - loss: 6.0046e-04 - val_loss: 3.0183e-04 - learning_rate: 1.5000e-04
Epoch 37/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 449ms/step - loss: 5.8415e-04
Epoch 37: val_loss did not improve from 0.00016
126/126 ━━━━━━━━━━━━━━━━━━━━ 61s 485ms/step - loss: 5.9534e-04 - val_loss: 3.9480e-04 - learning_rate: 1.5000e-04
Epoch 38/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 432ms/step - loss: 6.0139e-04
Epoch 38: val_loss did not improve from 0.00016
126/126 ━━━━━━━━━━━━━━━━━━━━ 58s 464ms/step - loss: 5.8792e-04 - val_loss: 1.9528e-04 - learning_rate: 1.5000e-04
Epoch 39/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 438ms/step - loss: 5.7265e-04
Epoch 39: val_loss did not improve from 0.00016
126/126 ━━━━━━━━━━━━━━━━━━━━ 59s 470ms/step - loss: 5.7517e-04 - val_loss: 1.7565e-04 - learning_rate: 1.5000e-04
Epoch 40/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 427ms/step - loss: 5.2826e-04
Epoch 40: val_loss did not improve from 0.00016
126/126 ━━━━━━━━━━━━━━━━━━━━ 58s 458ms/step - loss: 5.6347e-04 - val_loss: 1.7957e-04 - learning_rate: 1.5000e-04
Epoch 41/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 417ms/step - loss: 5.3902e-04
Epoch 41: val_loss did not improve from 0.00016

Epoch 41: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
126/126 ━━━━━━━━━━━━━━━━━━━━ 57s 449ms/step - loss: 5.5065e-04 - val_loss: 1.8492e-04 - learning_rate: 1.5000e-04
Epoch 42/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 417ms/step - loss: 4.9578e-04
Epoch 42: val_loss improved from 0.00016 to 0.00015, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 57s 450ms/step - loss: 5.1456e-04 - val_loss: 1.5331e-04 - learning_rate: 7.5000e-05
Epoch 43/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 406ms/step - loss: 5.2022e-04
Epoch 43: val_loss did not improve from 0.00015
126/126 ━━━━━━━━━━━━━━━━━━━━ 55s 434ms/step - loss: 5.2097e-04 - val_loss: 1.7016e-04 - learning_rate: 7.5000e-05
Epoch 44/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 404ms/step - loss: 4.8237e-04
Epoch 44: val_loss did not improve from 0.00015
126/126 ━━━━━━━━━━━━━━━━━━━━ 55s 435ms/step - loss: 5.0181e-04 - val_loss: 1.8166e-04 - learning_rate: 7.5000e-05
Epoch 45/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 402ms/step - loss: 5.0584e-04
Epoch 45: val_loss did not improve from 0.00015
126/126 ━━━━━━━━━━━━━━━━━━━━ 54s 431ms/step - loss: 5.0063e-04 - val_loss: 1.6694e-04 - learning_rate: 7.5000e-05
Epoch 46/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 263ms/step - loss: 5.1538e-04
Epoch 46: val_loss did not improve from 0.00015
126/126 ━━━━━━━━━━━━━━━━━━━━ 64s 288ms/step - loss: 5.1836e-04 - val_loss: 2.1680e-04 - learning_rate: 7.5000e-05
Epoch 47/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 354ms/step - loss: 4.9645e-04
Epoch 47: val_loss did not improve from 0.00015
126/126 ━━━━━━━━━━━━━━━━━━━━ 51s 403ms/step - loss: 5.0522e-04 - val_loss: 1.6523e-04 - learning_rate: 7.5000e-05
Epoch 48/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 287ms/step - loss: 4.9933e-04
Epoch 48: val_loss did not improve from 0.00015
126/126 ━━━━━━━━━━━━━━━━━━━━ 71s 316ms/step - loss: 5.0249e-04 - val_loss: 1.6955e-04 - learning_rate: 7.5000e-05
Epoch 49/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 388ms/step - loss: 4.8514e-04
Epoch 49: val_loss did not improve from 0.00015
126/126 ━━━━━━━━━━━━━━━━━━━━ 53s 418ms/step - loss: 4.8832e-04 - val_loss: 1.7192e-04 - learning_rate: 7.5000e-05
Epoch 50/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 401ms/step - loss: 4.9585e-04
Epoch 50: val_loss did not improve from 0.00015
126/126 ━━━━━━━━━━━━━━━━━━━━ 54s 429ms/step - loss: 4.7872e-04 - val_loss: 1.7111e-04 - learning_rate: 7.5000e-05
Epoch 51/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 405ms/step - loss: 4.8026e-04
Epoch 51: val_loss did not improve from 0.00015

Epoch 51: ReduceLROnPlateau reducing learning rate to 3.7500001781154424e-05.
126/126 ━━━━━━━━━━━━━━━━━━━━ 55s 440ms/step - loss: 4.8441e-04 - val_loss: 1.5975e-04 - learning_rate: 7.5000e-05
Epoch 52/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 407ms/step - loss: 4.5155e-04
Epoch 52: val_loss did not improve from 0.00015
126/126 ━━━━━━━━━━━━━━━━━━━━ 55s 438ms/step - loss: 4.6307e-04 - val_loss: 1.7848e-04 - learning_rate: 3.7500e-05
Epoch 53/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 402ms/step - loss: 4.5953e-04
Epoch 53: val_loss did not improve from 0.00015
126/126 ━━━━━━━━━━━━━━━━━━━━ 54s 431ms/step - loss: 4.6704e-04 - val_loss: 1.5659e-04 - learning_rate: 3.7500e-05
Epoch 54/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 387ms/step - loss: 4.3945e-04
Epoch 54: val_loss did not improve from 0.00015
126/126 ━━━━━━━━━━━━━━━━━━━━ 53s 420ms/step - loss: 4.4132e-04 - val_loss: 1.5365e-04 - learning_rate: 3.7500e-05
Epoch 55/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 387ms/step - loss: 4.4773e-04
Epoch 55: val_loss did not improve from 0.00015
126/126 ━━━━━━━━━━━━━━━━━━━━ 53s 418ms/step - loss: 4.4854e-04 - val_loss: 1.7388e-04 - learning_rate: 3.7500e-05
Epoch 56/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 398ms/step - loss: 4.7740e-04
Epoch 56: val_loss did not improve from 0.00015
126/126 ━━━━━━━━━━━━━━━━━━━━ 54s 431ms/step - loss: 4.7065e-04 - val_loss: 1.5629e-04 - learning_rate: 3.7500e-05
Epoch 57/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 391ms/step - loss: 4.6497e-04
Epoch 57: val_loss improved from 0.00015 to 0.00015, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 53s 423ms/step - loss: 4.4547e-04 - val_loss: 1.5160e-04 - learning_rate: 3.7500e-05
Epoch 58/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 394ms/step - loss: 4.5395e-04
Epoch 58: val_loss did not improve from 0.00015
126/126 ━━━━━━━━━━━━━━━━━━━━ 53s 424ms/step - loss: 4.5118e-04 - val_loss: 1.9929e-04 - learning_rate: 3.7500e-05
Epoch 59/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 392ms/step - loss: 4.5389e-04
Epoch 59: val_loss did not improve from 0.00015
126/126 ━━━━━━━━━━━━━━━━━━━━ 53s 421ms/step - loss: 4.4577e-04 - val_loss: 1.7069e-04 - learning_rate: 3.7500e-05
Epoch 60/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 401ms/step - loss: 4.5001e-04
Epoch 60: val_loss improved from 0.00015 to 0.00015, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 55s 436ms/step - loss: 4.4601e-04 - val_loss: 1.5063e-04 - learning_rate: 3.7500e-05
Epoch 61/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 372ms/step - loss: 4.4431e-04
Epoch 61: val_loss improved from 0.00015 to 0.00015, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras

Epoch 61: ReduceLROnPlateau reducing learning rate to 1.8750000890577212e-05.
126/126 ━━━━━━━━━━━━━━━━━━━━ 51s 408ms/step - loss: 4.4631e-04 - val_loss: 1.4674e-04 - learning_rate: 3.7500e-05
Epoch 62/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 403ms/step - loss: 4.3094e-04
Epoch 62: val_loss improved from 0.00015 to 0.00014, saving model to c:\Users\huyy\AirPollutionPrediction-CNN-BiLSTM\artifacts\cnn_bilstm_station1_24havg_seq48_u128.keras
126/126 ━━━━━━━━━━━━━━━━━━━━ 55s 435ms/step - loss: 4.2140e-04 - val_loss: 1.4202e-04 - learning_rate: 1.8750e-05
Epoch 63/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 408ms/step - loss: 4.2575e-04
Epoch 63: val_loss did not improve from 0.00014
126/126 ━━━━━━━━━━━━━━━━━━━━ 55s 435ms/step - loss: 4.2018e-04 - val_loss: 1.4722e-04 - learning_rate: 1.8750e-05
Epoch 64/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 395ms/step - loss: 4.3692e-04
Epoch 64: val_loss did not improve from 0.00014
126/126 ━━━━━━━━━━━━━━━━━━━━ 54s 428ms/step - loss: 4.2802e-04 - val_loss: 1.5143e-04 - learning_rate: 1.8750e-05
Epoch 65/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 402ms/step - loss: 4.2861e-04
Epoch 65: val_loss did not improve from 0.00014
126/126 ━━━━━━━━━━━━━━━━━━━━ 54s 431ms/step - loss: 4.2402e-04 - val_loss: 1.4788e-04 - learning_rate: 1.8750e-05
Epoch 66/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 388ms/step - loss: 4.2892e-04
Epoch 66: val_loss did not improve from 0.00014
126/126 ━━━━━━━━━━━━━━━━━━━━ 53s 422ms/step - loss: 4.3267e-04 - val_loss: 1.4408e-04 - learning_rate: 1.8750e-05
Epoch 67/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 395ms/step - loss: 4.3009e-04
Epoch 67: val_loss did not improve from 0.00014
126/126 ━━━━━━━━━━━━━━━━━━━━ 53s 424ms/step - loss: 4.2379e-04 - val_loss: 1.4557e-04 - learning_rate: 1.8750e-05
Epoch 68/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 398ms/step - loss: 4.2977e-04
Epoch 68: val_loss did not improve from 0.00014
126/126 ━━━━━━━━━━━━━━━━━━━━ 54s 431ms/step - loss: 4.3211e-04 - val_loss: 1.4820e-04 - learning_rate: 1.8750e-05
Epoch 69/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 394ms/step - loss: 4.2719e-04
Epoch 69: val_loss did not improve from 0.00014
126/126 ━━━━━━━━━━━━━━━━━━━━ 53s 423ms/step - loss: 4.1583e-04 - val_loss: 1.4413e-04 - learning_rate: 1.8750e-05
Epoch 70/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 384ms/step - loss: 4.3338e-04
Epoch 70: val_loss did not improve from 0.00014
126/126 ━━━━━━━━━━━━━━━━━━━━ 52s 413ms/step - loss: 4.2283e-04 - val_loss: 1.5287e-04 - learning_rate: 1.8750e-05
Epoch 71/200
126/126 ━━━━━━━━━━━━━━━━━━━━ 0s 293ms/step - loss: 4.1860e-04
Epoch 71: val_loss did not improve from 0.00014

Epoch 71: ReduceLROnPlateau reducing learning rate to 9.375000445288606e-06.
126/126 ━━━━━━━━━━━━━━━━━━━━ 70s 319ms/step - loss: 4.2299e-04 - val_loss: 1.4252e-04 - learning_rate: 1.8750e-05
Epoch 72/200

   Station_No  n_test  Correlation       RMSE      MAPE       MAE
0           1    1688     0.985773  10.531547  0.102112  7.101685
1           2    1688     0.995178   3.207941  0.019301  2.395723
2           3    1688     0.996437   4.629591  0.031493  3.398873
3           4    1688     0.995880   5.245996  0.022811  3.982021
4           5    1688     0.982340  12.117559  0.120535  7.660173
5           6    1685     0.995141   5.275030  0.031820  4.194633

In [13]:
print("\nMean across stations:")
print(results_df[["Correlation","RMSE","MAE","MAPE"]].mean())

print("\nMAPE median:", results_df["MAPE"].median())

Mean across stations:
Correlation    0.991791
RMSE           6.834611
MAE            4.788851
MAPE           0.054679
dtype: float64

MAPE median: 0.031656717881560326

In [14]:
paper_table2 = pd.DataFrame({
    "Station_No":[1,2,3,4,5,6],
    "RMSE":[9.58,9.47,16.63,15.67,7.30,10.03],
    "MAPE":[0.54,0.34,0.54,0.39,0.31,0.31],
    "MAE":[7.12,6.35,11.09,9.44,4.89,6.00],
    "Correlation":[0.34,0.49,0.50,0.37,0.46,0.44]
})

paper_table1 = pd.DataFrame({
    "Station_No":[1,2,3,4,5,6],
    "RMSE":[7.22,7.72,12.34,9.83,4.85,5.94],
    "MAPE":[0.27,0.23,0.33,0.24,0.20,0.20],
    "MAE":[5.32,4.76,8.01,6.37,3.36,3.94],
    "Correlation":[0.70,0.71,0.69,0.71,0.72,0.77]
})

paper_table1, paper_table2

(   Station_No   RMSE  MAPE   MAE  Correlation
 0           1   7.22  0.27  5.32         0.70
 1           2   7.72  0.23  4.76         0.71
 2           3  12.34  0.33  8.01         0.69
 3           4   9.83  0.24  6.37         0.71
 4           5   4.85  0.20  3.36         0.72
 5           6   5.94  0.20  3.94         0.77,
    Station_No   RMSE  MAPE    MAE  Correlation
 0           1   9.58  0.54   7.12         0.34
 1           2   9.47  0.34   6.35         0.49
 2           3  16.63  0.54  11.09         0.50
 3           4  15.67  0.39   9.44         0.37
 4           5   7.30  0.31   4.89         0.46
 5           6  10.03  0.31   6.00         0.44)

rolling mean

In [15]:
cmp1 = results_df.merge(paper_table1, on="Station_No", suffixes=("_yours", "_paper1"))
cmp1["RMSE_gain"] = cmp1["RMSE_paper1"] - cmp1["RMSE_yours"]
cmp1["MAE_gain"]  = cmp1["MAE_paper1"]  - cmp1["MAE_yours"]
cmp1["Corr_gain"] = cmp1["Correlation_yours"] - cmp1["Correlation_paper1"]
cmp1[["Station_No","RMSE_yours","RMSE_paper1","RMSE_gain","MAE_yours","MAE_paper1","MAE_gain","Correlation_yours","Correlation_paper1","Corr_gain","MAPE_yours","MAPE_paper1"]]

,Station_No,RMSE_yours,RMSE_paper1,RMSE_gain,MAE_yours,MAE_paper1,MAE_gain,Correlation_yours,Correlation_paper1,Corr_gain,MAPE_yours,MAPE_paper1
0,1,10.531547,7.22,-3.311547,7.101685,5.32,-1.781685,0.985773,0.70,0.285773,0.102112,0.27
1,2,3.207941,7.72,4.512059,2.395723,4.76,2.364277,0.995178,0.71,0.285178,0.019301,0.23
2,3,4.629591,12.34,7.710409,3.398873,8.01,4.611127,0.996437,0.69,0.306437,0.031493,0.33
3,4,5.245996,9.83,4.584004,3.982021,6.37,2.387979,0.995880,0.71,0.285880,0.022811,0.24
4,5,12.117559,4.85,-7.267559,7.660173,3.36,-4.300173,0.982340,0.72,0.262340,0.120535,0.20
5,6,5.275030,5.94,0.664970,4.194633,3.94,-0.254633,0.995141,0.77,0.225141,0.031820,0.20

Mean compare

In [16]:
mean_yours = results_df[["Correlation","RMSE","MAE","MAPE"]].mean()
mean_p1 = paper_table1[["Correlation","RMSE","MAE","MAPE"]].mean()
mean_p2 = paper_table2[["Correlation","RMSE","MAE","MAPE"]].mean()

summary_compare = pd.DataFrame({
    "Yours_24havg": mean_yours,
    "Paper_Table1_with_rollmean": mean_p1,
    "Paper_Table2_no_rollmean": mean_p2
})
summary_compare

,Yours_24havg,Paper_Table1_with_rollmean,Paper_Table2_no_rollmean
Correlation,0.991791,0.716667,0.433333
RMSE,6.834611,7.983333,11.446667
MAE,4.788851,5.293333,7.481667
MAPE,0.054679,0.245000,0.405000

Kiểm tra có bị overlift kh

In [28]:
from pathlib import Path
import pandas as pd

STATION_SPLIT_DIR = STATION_SPLIT_DIR  # đã define trước

for st_dir in sorted(STATION_SPLIT_DIR.glob("station_*"),
                     key=lambda p: int(p.name.split("_")[1])):

    st = int(st_dir.name.split("_")[1])

    train_df = pd.read_csv(st_dir / "train.csv")
    val_df   = pd.read_csv(st_dir / "val.csv")
    test_df  = pd.read_csv(st_dir / "test.csv")

    train_df["date"] = pd.to_datetime(train_df["date"])
    val_df["date"]   = pd.to_datetime(val_df["date"])
    test_df["date"]  = pd.to_datetime(test_df["date"])

    print(f"\nStation {st}")
    print("Train:", train_df["date"].min(), "->", train_df["date"].max())
    print("Val  :", val_df["date"].min(),   "->", val_df["date"].max())
    print("Test :", test_df["date"].min(),  "->", test_df["date"].max())

    # kiểm tra overlap
    assert train_df["date"].max() < val_df["date"].min(), "Train/Val overlap!"
    assert val_df["date"].max()   < test_df["date"].min(), "Val/Test overlap!"

print("\n Time-based split OK (no shuffle, no overlap)")

Station 1
Train: 2021-02-24 20:00:00 -> 2022-01-28 03:00:00
Val  : 2022-01-28 04:00:00 -> 2022-04-10 09:00:00
Test : 2022-04-10 10:00:00 -> 2022-06-21 17:00:00

Station 2
Train: 2021-02-24 20:00:00 -> 2022-01-28 03:00:00
Val  : 2022-01-28 04:00:00 -> 2022-04-10 09:00:00
Test : 2022-04-10 10:00:00 -> 2022-06-21 17:00:00

Station 3
Train: 2021-02-24 20:00:00 -> 2022-01-28 03:00:00
Val  : 2022-01-28 04:00:00 -> 2022-04-10 09:00:00
Test : 2022-04-10 10:00:00 -> 2022-06-21 17:00:00

Station 4
Train: 2021-02-24 20:00:00 -> 2022-01-28 03:00:00
Val  : 2022-01-28 04:00:00 -> 2022-04-10 09:00:00
Test : 2022-04-10 10:00:00 -> 2022-06-21 17:00:00

Station 5
Train: 2021-02-24 20:00:00 -> 2022-01-28 03:00:00
Val  : 2022-01-28 04:00:00 -> 2022-04-10 09:00:00
Test : 2022-04-10 10:00:00 -> 2022-06-21 17:00:00

Station 6
Train: 2021-02-25 15:00:00 -> 2022-01-28 08:00:00
Val  : 2022-01-28 09:00:00 -> 2022-04-10 12:00:00
Test : 2022-04-10 13:00:00 -> 2022-06-21 17:00:00

 Time-based split OK (no shuffle, no overlap)

In [27]:
SEQ_LEN = 48  # đang dùng

for st_dir in sorted(STATION_SPLIT_DIR.glob("station_*"),
                     key=lambda p: int(p.name.split("_")[1])):

    st = int(st_dir.name.split("_")[1])

    train_df = pd.read_csv(st_dir / "train.csv")
    test_df  = pd.read_csv(st_dir / "test.csv")

    train_df["date"] = pd.to_datetime(train_df["date"])
    test_df["date"]  = pd.to_datetime(test_df["date"])

    last_train = train_df["date"].max()
    first_test = test_df["date"].min()

    gap_hours = (first_test - last_train).total_seconds() / 3600

    print(f"Station {st}: gap_hours =", gap_hours)

    if gap_hours < 0:
        print(" Overlap detected")
    else:
        print("OK")

print("\nNote: gap=1h là bình thường vì test dùng quá khứ từ test set, không từ train.")

Station 1: gap_hours = 1735.0
OK
Station 2: gap_hours = 1735.0
OK
Station 3: gap_hours = 1735.0
OK
Station 4: gap_hours = 1735.0
OK
Station 5: gap_hours = 1735.0
OK
Station 6: gap_hours = 1733.0
OK

Note: gap=1h là bình thường vì test dùng quá khứ từ test set, không từ train.

In [25]:
import pandas as pd

st_dir = STATION_SPLIT_DIR / "station_1"

train_df = pd.read_csv(st_dir / "train.csv")
train_df["date"] = pd.to_datetime(train_df["date"])
train_df = train_df.sort_values("date").reset_index(drop=True)

# tự tính rolling mean 24h
manual_roll = train_df["PM2.5"].rolling(window=24, min_periods=24).mean()

diff = (manual_roll - train_df["PM2.5_24h_avg"]).abs()

print("Max difference:", diff.max())

Max difference: 1.1102230246251565e-16

In [26]:
# kiểm tra feature leakage sơ bộ
st_dir = STATION_SPLIT_DIR / "station_1"

train_df = pd.read_csv(st_dir / "train.csv")
test_df  = pd.read_csv(st_dir / "test.csv")

target_col = "PM2.5_24h_avg"
id_cols = ["Station_No","date"]

feature_cols = [c for c in train_df.columns if c not in id_cols + [target_col]]

corrs = []

for col in feature_cols:
    c = test_df[[col, target_col]].corr().iloc[0,1]
    corrs.append((col, c))

corrs_sorted = sorted(corrs, key=lambda x: abs(x[1]), reverse=True)

print("Top 10 feature correlations with target in test:")
for col, c in corrs_sorted[:10]:
    print(col, ":", c)

Top 10 feature correlations with target in test:
O3 : nan
NO2 : nan
SO2 : nan
PM2.5_roll12_mean : 0.8685471235295746
PM2.5_lag12 : 0.7994135797929961
PM2.5_lag6 : 0.7540451673194263
PM2.5_roll6_mean : 0.7305766032297427
PM2.5_lag3 : 0.6899184872163892
PM2.5_lag2 : 0.6607771252983659
PM2.5_roll3 : 0.6486054610619079